/**
 * Pure array transforms and session-orchestration for the workbench entry
 * and the "my workflows" menu group: the workflow and group lists a write
 * replaces whole, the derived views the menu renders (pinned groups, the rest,
 * one group's members, the ungrouped remainder, and the temporary group of
 * conversations nothing else lists), and the two clicks that need the session
 * domain. Persistence (the HTTP round trip through `workflow-api.ts`) and
 * reactive-store wiring stay in `client/index.ts`, which is the one place
 * both this package's `sidebar` registration and its
 * `conversation.session.header.actions` registration are composed together.
 * @module @deepseek-ai/dsh-experimental-server-sidebar/client/workflow-actions
 */
import type { Context as ClientContext } from '@deepseek-ai/cordis'
import type { SessionId } from '@deepseek-ai/dsh-session/types'
import { resolveOrCreateSession } from './session-resolution.ts'
import { replayNavSnapshot } from './open-nav.ts'
import { surfaceKindOf } from './nav-snapshot.ts'
import type { NavSnapshotItem, ServerMenuGroup, ServerMenuWorkflow } from './workflow-api.ts'

/**
 * Compute the next display order for an appended workflow: one past the current highest.
 * @param workflows - the current workflow list.
 * @returns the order value the newly appended workflow should carry.
 */
export function nextOrder(workflows: readonly ServerMenuWorkflow[]): number {
  return workflows.reduce((max, workflow) => Math.max(max, workflow.order), -1) + 1
}

/**
 * Sort workflows for display: user-dragged order, ties broken on id for a stable render.
 * @param workflows - the workflows to sort; not mutated.
 * @returns a new array sorted by `order` ascending, ties broken by `id`.
 */
export function sortedWorkflows(workflows: readonly ServerMenuWorkflow[]): ServerMenuWorkflow[] {
  return [...workflows].sort((left, right) => left.order - right.order || (left.id < right.id ? -1 : 1))
}

/**
 * Compute the next display order for an appended group: one past the current highest.
 * @param groups - the current group list.
 * @returns the order value the newly appended group should carry.
 */
function nextGroupOrder(groups: readonly ServerMenuGroup[]): number {
  return groups.reduce((max, group) => Math.max(max, group.order), -1) + 1
}

/**
 * Add one group, unpinned, after every existing one.
 * @param groups - the current group list; not mutated.
 * @param id - the new group's stable id, generated by the caller (the same
 * `crypto.randomUUID()` a saved workflow's id comes from) so this transform
 * stays pure.
 * @param name - the user's typed name; stored trimmed.
 * @returns the complete next group list.
 */
export function createGroup(groups: readonly ServerMenuGroup[], id: string, name: string): ServerMenuGroup[] {
  return [...groups, { id, name: name.trim(), pinned: false, order: nextGroupOrder(groups) }]
}

/**
 * Rename one group.
 * @param groups - the current group list; not mutated.
 * @param groupId - the group to rename.
 * @param name - the user's typed name; stored trimmed.
 * @returns the complete next group list; an unchanged copy when `groupId`
 * names no group.
 */
export function renameGroup(groups: readonly ServerMenuGroup[], groupId: string, name: string): ServerMenuGroup[] {
  return groups.map(group => (group.id === groupId ? { ...group, name: name.trim() } : group))
}

/**
 * Pin or unpin one group.
 * @param groups - the current group list; not mutated.
 * @param groupId - the group to change.
 * @param pinned - whether it should sort ahead of every unpinned group.
 * @returns the complete next group list; an unchanged copy when `groupId`
 * names no group.
 */
export function pinGroup(groups: readonly ServerMenuGroup[], groupId: string, pinned: boolean): ServerMenuGroup[] {
  return groups.map(group => (group.id === groupId ? { ...group, pinned } : group))
}

/**
 * File one workflow under a group (or under none), at the given display order.
 * @param workflow - the workflow to re-file; not mutated.
 * @param groupId - the destination group's id, or `undefined` for ungrouped,
 * which drops the field rather than storing an empty value.
 * @param order - the display order the result carries.
 * @returns the re-filed workflow.
 */
function filed(workflow: ServerMenuWorkflow, groupId: string | undefined, order: number): ServerMenuWorkflow {
  const next: ServerMenuWorkflow = { ...workflow, order }
  if (groupId === undefined) delete next.groupId
  else next.groupId = groupId
  return next
}

/** The two lists a group deletion rewrites, which have to travel in one patch (see {@link deleteGroup}). */
export interface GroupDeletion {
  /** The complete next group list. */
  groups: ServerMenuGroup[]
  /** The complete next workflow list. */
  workflows: ServerMenuWorkflow[]
}

/**
 * Delete one group and return its members to the ungrouped list. Both lists
 * belong to a single patch: the route validates the merged document, which
 * refuses a workflow filed under a group nothing defines, so a patch carrying
 * only the shortened group list would be rejected.
 * @param groups - the current group list; not mutated.
 * @param workflows - the current workflow list; not mutated.
 * @param groupId - the group to delete.
 * @returns both complete next lists.
 */
export function deleteGroup(
  groups: readonly ServerMenuGroup[], workflows: readonly ServerMenuWorkflow[], groupId: string,
): GroupDeletion {
  return {
    groups: groups.filter(group => group.id !== groupId),
    workflows: workflows.map(workflow => (workflow.groupId === groupId ? filed(workflow, undefined, workflow.order) : workflow)),
  }
}

/**
 * Move one workflow into a group (or out of every group), landing it last
 * among that destination's current members.
 * @param workflows - the current workflow list; not mutated.
 * @param workflowId - the workflow to move.
 * @param groupId - the destination group's id, or `undefined` for the
 * ungrouped list.
 * @returns the complete next workflow list; an unchanged copy when
 * `workflowId` names no workflow.
 */
export function moveWorkflow(
  workflows: readonly ServerMenuWorkflow[], workflowId: string, groupId: string | undefined,
): ServerMenuWorkflow[] {
  const order = nextOrder(workflows.filter(workflow => workflow.id !== workflowId && workflow.groupId === groupId))
  return workflows.map(workflow => (workflow.id === workflowId ? filed(workflow, groupId, order) : workflow))
}

/**
 * Sort groups for display: pinned first, then user-dragged order, ties broken
 * on id for a stable render.
 * @param groups - the groups to sort; not mutated.
 * @returns a new array in display order.
 */
function sortedGroups(groups: readonly ServerMenuGroup[]): ServerMenuGroup[] {
  return [...groups].sort((left, right) =>
    Number(right.pinned) - Number(left.pinned) || left.order - right.order || (left.id < right.id ? -1 : 1))
}

/**
 * State one section's complete next contents: every workflow named in `ids`
 * is filed under `groupId` at its position in the sequence. This is both the
 * within-group reorder and the drop-target half of a cross-group drag — a row
 * dragged in from elsewhere is named in the destination's sequence and is
 * re-filed by the same call.
 * @param workflows - the current workflow list; not mutated.
 * @param groupId - the section's group id, or `undefined` for the ungrouped
 * list.
 * @param ids - the section's complete next display sequence; an id naming no
 * workflow is ignored, and a workflow no id names is left untouched (still
 * filed where it was, at the order it had).
 * @returns the complete next workflow list.
 */
export function reorderWithinGroup(
  workflows: readonly ServerMenuWorkflow[], groupId: string | undefined, ids: readonly string[],
): ServerMenuWorkflow[] {
  const positions = new Map(ids.filter(id => workflows.some(workflow => workflow.id === id)).map((id, index) => [id, index]))
  return workflows.map((workflow) => {
    const order = positions.get(workflow.id)
    return order === undefined ? workflow : filed(workflow, groupId, order)
  })
}

/**
 * The groups that sort ahead of the rest.
 * @param groups - the current group list; not mutated.
 * @returns the pinned groups in display order.
 */
export function pinnedGroups(groups: readonly ServerMenuGroup[]): ServerMenuGroup[] {
  return sortedGroups(groups).filter(group => group.pinned)
}

/**
 * The groups that sort after every pinned one.
 * @param groups - the current group list; not mutated.
 * @returns the unpinned groups in display order.
 */
export function otherGroups(groups: readonly ServerMenuGroup[]): ServerMenuGroup[] {
  return sortedGroups(groups).filter(group => !group.pinned)
}

/**
 * One group's workflows.
 * @param workflows - the current workflow list; not mutated.
 * @param groupId - the group whose members to collect.
 * @returns that group's workflows in display order.
 */
export function workflowsInGroup(workflows: readonly ServerMenuWorkflow[], groupId: string): ServerMenuWorkflow[] {
  return sortedWorkflows(workflows.filter(workflow => workflow.groupId === groupId))
}

/**
 * The workflows that belong to no group, which the menu shows at its own top
 * level. A workflow naming a group nothing defines counts as ungrouped rather
 * than disappearing: the document's own constraint refuses such a reference,
 * so this only arises from a document edited outside the interface, and every
 * workflow has to be reachable from somewhere.
 * @param workflows - the current workflow list; not mutated.
 * @param groups - the current group list, which decides what a stored
 * `groupId` resolves against.
 * @returns the ungrouped workflows in display order.
 */
export function ungroupedWorkflows(
  workflows: readonly ServerMenuWorkflow[], groups: readonly ServerMenuGroup[],
): ServerMenuWorkflow[] {
  return sortedWorkflows(workflows.filter(workflow =>
    workflow.groupId === undefined || !groups.some(group => group.id === workflow.groupId)))
}

/**
 * The session facts the temporary group derives its membership and order
 * from — the subset of `SessionSummary` (`dsh-client-store`) this module
 * reads, so the derivation is testable without building a whole session list.
 */
export interface TemporarySessionFacts {
  /** The session's id. */
  readonly id: string
  /** Whether the session has yet to run a conversation turn. */
  readonly blank: boolean
  /** Creation time, or the last human prompt's time when that is later (epoch ms). */
  readonly updatedAt: number
  /** Coarse durable origin; `'subagent'` rows belong to their parent's own catalog. */
  readonly origin?: 'subagent'
}

/** What the temporary group's membership is decided against (see {@link temporarySessions}). */
export interface TemporaryGroupScope {
  /** Every session a workflow currently binds, which the workflow's own row already shows. */
  boundHomeSessionIds: ReadonlySet<string>
  /** The workbench conversation's id, which the workbench entry already shows. */
  workbenchSessionId: string | undefined
  /** The selected session, which keeps a blank draft visible while it is on screen. */
  currentSessionId: string | undefined
  /** Sessions taken out of the list (`ctx.workspaces.archiveSession`). */
  archivedSessionIds: ReadonlySet<string>
}

/**
 * Derive the temporary group: the conversations that exist but have no row
 * of their own anywhere else in this shell. Five predicates decide
 * membership — not a subagent child, not archived, not the workbench, not any
 * workflow's bound conversation, and not a blank draft unless it is the one
 * currently selected (otherwise every visit to the workbench would leave a
 * nameless empty row behind).
 * @param sessions - every session in the directory; not mutated. The caller
 * resolves the session list's ids against its `byId` map.
 * @param scope - what membership is decided against (see {@link TemporaryGroupScope}).
 * @returns the members, most recently updated first, ties broken on id.
 */
export function temporarySessions<T extends TemporarySessionFacts>(
  sessions: readonly T[], scope: TemporaryGroupScope,
): T[] {
  return sessions
    .filter(session => session.origin !== 'subagent'
      && !scope.archivedSessionIds.has(session.id)
      && session.id !== scope.workbenchSessionId
      && !scope.boundHomeSessionIds.has(session.id)
      && (!session.blank || session.id === scope.currentSessionId))
    .sort((left, right) => right.updatedAt - left.updatedAt || (left.id < right.id ? -1 : 1))
}

/**
 * Rows the temporary group shows before a user asks for the rest. Matches the
 * shipped browser's own collapsed session limit: enough to recognize what was
 * left open, short enough that the group never crowds out the menu above it.
 */
export const TEMPORARY_VISIBLE_LIMIT = 5

/** A list cut to its collapsed length, and how much is left over (see {@link collapsedRows}). */
export interface CollapsedRows<T> {
  /** The rows to render. */
  visible: T[]
  /** How many rows the collapsed view leaves out; `0` when nothing is hidden. */
  hiddenCount: number
}

/**
 * Cut a row list to {@link TEMPORARY_VISIBLE_LIMIT} until the group is
 * expanded — an explicit two-state view (first few, or all), not paging.
 * @param rows - the rows in display order; not mutated.
 * @param expanded - whether the user asked for the rest.
 * @returns the rows to render and how many are left out.
 */
export function collapsedRows<T>(rows: readonly T[], expanded: boolean): CollapsedRows<T> {
  if (expanded) return { visible: [...rows], hiddenCount: 0 }
  return { visible: rows.slice(0, TEMPORARY_VISIBLE_LIMIT), hiddenCount: Math.max(rows.length - TEMPORARY_VISIBLE_LIMIT, 0) }
}

/** Outcome of opening the workbench or a workflow: the session now open, and whether it was (re-)created. */
export interface OpenOutcome {
  /** The session now open. */
  sessionId: string
  /** Whether this call created a fresh session (workbench first use, or a workflow's degraded re-creation). */
  created: boolean
}

/**
 * Defensively-typed shape of one content-surface entry, read off
 * `SessionSummary.projectionValues.contentSurface.entries` (see
 * `ServerSidebarRoot.tsx`'s own read, which mirrors
 * `dsh-experimental-server-layout`'s `ShellFrame`): `isCleanWorkbenchDraft`
 * and `hasShownHome` only ever compare these two fields, so nothing else
 * about the real `ContentSurfaceEntry`
 * (`@deepseek-ai/dsh-experimental-content-surface/types`) needs to reach
 * this module.
 */
export interface ContentSurfaceEntryLike {
  /** The extractor kind that produced the entry; `'page'` for a content-frame page, `'component'` for a view. */
  readonly kind?: unknown
  /** Identity within the kind; a page entry's id is the page id, a component entry's is the view id. */
  readonly entryId?: unknown
}

/**
 * Whether one content-surface entry is the deployment's configured automatic
 * home, compared in the content-surface vocabulary the entry itself carries
 * (see `nav-snapshot.ts`'s `surfaceKindOf`).
 * @param entry - one entry, of unknown shape.
 * @param home - the configured home target.
 * @returns whether the entry is that target.
 */
function isHomeEntry(entry: ContentSurfaceEntryLike, home: NavSnapshotItem): boolean {
  return entry.kind === surfaceKindOf(home.kind) && entry.entryId === home.entryId
}

/**
 * Whether a workbench draft counts as clean for {@link openWorkbenchOnClick}'s
 * reuse decision: it has not run a conversation turn, and its content column
 * carries nothing beyond the deployment's own configured automatic home — a
 * menu click, a chart the agent drew, or any other content all disqualify it,
 * while the home target itself does not, since a clean click's own auto-open
 * step (`client/index.ts`'s `onOpenWorkbench`) is expected to have put it
 * there.
 * @param isBlank - `SessionSummary.blank`: whether the session has run a turn.
 * @param entries - the session's content-surface entries (see {@link ContentSurfaceEntryLike}).
 * @param home - the deployment's configured automatic home, or `undefined`
 * when none is configured — with no home, any entry at all disqualifies the
 * draft, since none can satisfy the exception.
 * @returns whether the draft is clean.
 */
export function isCleanWorkbenchDraft(
  isBlank: boolean, entries: readonly ContentSurfaceEntryLike[], home: NavSnapshotItem | undefined,
): boolean {
  return isBlank && (home === undefined ? entries.length === 0 : entries.every(entry => isHomeEntry(entry, home)))
}

/**
 * Whether entries already carry the deployment's configured automatic home —
 * consulted only when a click reuses a clean draft, so the click path's own
 * auto-open step (`client/index.ts`'s `onOpenWorkbench`) does not re-append an
 * identical record onto a draft that already carries one.
 * @param entries - the session's content-surface entries (see {@link ContentSurfaceEntryLike}).
 * @param home - the deployment's configured automatic home, or `undefined`
 * when none is configured.
 * @returns whether one entry is that target.
 */
export function hasShownHome(entries: readonly ContentSurfaceEntryLike[], home: NavSnapshotItem | undefined): boolean {
  return home !== undefined && entries.some(entry => isHomeEntry(entry, home))
}

/**
 * Shared workbench open-or-create mechanism: reopen the recorded session
 * when `reuse` holds, otherwise create a fresh one against the recent
 * Workspace and report it as newly created. `openWorkbenchOnLoad` and
 * `openWorkbenchOnClick` differ only in what `reuse` requires of the
 * recorded session — see each for its own semantics.
 * @param ctx - client root context.
 * @param workbenchSessionId - the recorded id, or `undefined` before first use.
 * @param reuse - whether the recorded session qualifies for reuse; when
 * `false` (or `workbenchSessionId` is `undefined`), a fresh session is
 * always created.
 * @returns the outcome, or `undefined` when there was nowhere to create a
 * session (no Workspace at all) — a contained no-op.
 */
async function openOrCreateWorkbench(
  ctx: ClientContext, workbenchSessionId: string | undefined, reuse: boolean,
): Promise<OpenOutcome | undefined> {
  if (reuse && workbenchSessionId !== undefined) {
    ctx.sessions.open(workbenchSessionId as SessionId)
    return { sessionId: workbenchSessionId, created: false }
  }
  const sessionId = await resolveOrCreateSession(ctx, {
    reuseCurrent: false,
    onNoWorkspace: 'server-sidebar: no workspace available to open the workbench',
  })
  return sessionId === undefined ? undefined : { sessionId, created: true }
}

/**
 * Open the workbench when the sidebar first loads with no session selected:
 * continuity semantics. Reopens the recorded session whenever it is still
 * live, whatever content it already carries — the page resumes exactly
 * where it left off. Re-creates only when the recorded session is gone, the
 * same weak-reference degrade a workflow's `homeSessionId` gets (decision ⑧
 * applies to the workbench too, since it is a weak reference by the same
 * reasoning). Contrast {@link openWorkbenchOnClick}, which additionally
 * requires the recorded session to still be clean.
 * @param ctx - client root context.
 * @param workbenchSessionId - the recorded id, or `undefined` before first use.
 * @param isLive - whether that id names a session the workspace domain still lists.
 * @returns the outcome, or `undefined` when there was nowhere to create a
 * session (no Workspace at all) — a contained no-op.
 */
export async function openWorkbenchOnLoad(
  ctx: ClientContext, workbenchSessionId: string | undefined, isLive: boolean,
): Promise<OpenOutcome | undefined> {
  return openOrCreateWorkbench(ctx, workbenchSessionId, isLive)
}

/**
 * Open the workbench on an explicit click: clean-draft semantics. A click
 * always lands on a clean page, so the recorded session reopens only when it
 * is both live and still clean (see {@link isCleanWorkbenchDraft}: no turn
 * run, and its content column carries nothing beyond the deployment's own
 * configured home page); otherwise a fresh session is created and the caller
 * must repoint `workbenchSessionId` at it (see `client/index.ts`'s `created`
 * handling). The displaced session is not deleted — see the package README's
 * Workflows section for what keeps it reachable. Contrast
 * {@link openWorkbenchOnLoad}, which reopens a live session regardless of its
 * content.
 * @param ctx - client root context.
 * @param workbenchSessionId - the recorded id, or `undefined` before first use.
 * @param isLive - whether that id names a session the workspace domain still lists.
 * @param isClean - whether that session is a clean draft (see
 * {@link isCleanWorkbenchDraft}); irrelevant (and never consulted) when
 * `isLive` is `false`.
 * @returns the outcome, or `undefined` when there was nowhere to create a
 * session (no Workspace at all) — a contained no-op.
 */
export async function openWorkbenchOnClick(
  ctx: ClientContext, workbenchSessionId: string | undefined, isLive: boolean, isClean: boolean,
): Promise<OpenOutcome | undefined> {
  return openOrCreateWorkbench(ctx, workbenchSessionId, isLive && isClean)
}

/**
 * Open a workflow: switch to its bound conversation when live, or degrade
 * (decision ⑧) by creating a fresh one and replaying the captured
 * navigation snapshot onto it — "only fill in what is missing" is trivially
 * satisfied because the fresh session starts empty.
 * @param ctx - client root context.
 * @param workflow - the workflow to open.
 * @param isLive - whether `workflow.homeSessionId` names a session the
 * workspace domain still lists.
 * @returns the outcome, or `undefined` when there was nowhere to create a
 * session (no Workspace at all) — a contained no-op.
 */
export async function openWorkflow(
  ctx: ClientContext, workflow: ServerMenuWorkflow, isLive: boolean,
): Promise<OpenOutcome | undefined> {
  if (isLive) {
    ctx.sessions.open(workflow.homeSessionId as SessionId)
    return { sessionId: workflow.homeSessionId, created: false }
  }
  const sessionId = await resolveOrCreateSession(ctx, {
    reuseCurrent: false,
    onNoWorkspace: 'server-sidebar: no workspace available to re-create this workflow\'s conversation',
  })
  if (sessionId === undefined) return undefined
  await replayNavSnapshot(ctx, sessionId, workflow.navSnapshot)
  return { sessionId, created: true }
}

/**
 * Open one conversation from the temporary group. Every member of that group
 * is read out of the live session list itself (see {@link temporarySessions}),
 * so there is no stale id to degrade around the way a workflow's recorded
 * conversation can be — this selects it and nothing more.
 * @param ctx - client root context.
 * @param sessionId - the conversation to select.
 * @returns an already-resolved promise, so this callback matches the
 * asynchronous face its seat declares alongside its dismiss sibling.
 */
export function openTemporarySession(ctx: ClientContext, sessionId: string): Promise<void> {
  ctx.sessions.open(sessionId as SessionId)
  return Promise.resolve()
}

/**
 * Take one conversation out of the temporary group. Archives it, which hides
 * it from every view derived from the session directory while leaving its log
 * and its accounting slot in place — nothing here deletes a conversation.
 * This shell offers no way back: no interface in it unarchives, so the caller
 * confirms the click before spending it (see the package README's Known
 * Limitations).
 * @param ctx - client root context.
 * @param sessionId - the conversation to take out of the list.
 * @returns a promise settling when the archive round trip finishes.
 * @throws {Error} when the archive call fails; the message is the host
 * runtime's own (`session archive failed: …`), so the caller logs it and
 * reports the refusal to the person in this section's fixed copy.
 */
export async function dismissTemporarySession(ctx: ClientContext, sessionId: string): Promise<void> {
  await ctx.workspaces.archiveSession(sessionId as SessionId)
}
