/**
 * What one `show_component` call is from outside the tool body, and what one
 * action reported back out of a drawn block is: the wire tool name, the command
 * name the seat reports through, the content kind the call claims, the catalog
 * of components a call may place with the actions each of them reports and the
 * values another block may read from them, the layout tree a call arranges its
 * blocks in, and the protocol ceilings both directions are measured against.
 *
 * One home, because three readers must agree on the same rules. The tool
 * refuses a call the seat could not draw; the content-surface extractor decides
 * which logged calls became entries; and the browser seat re-reads the same
 * document at the wire edge, where a value's type is a claim rather than a
 * guarantee. A component the host accepts and the seat refuses is a blank
 * column with nothing said about it, and a ceiling the two halves disagree on
 * is that same failure with an extra round trip in front of it.
 *
 * The module imports nothing, so the node half, the browser bundle, and the
 * session fold all read one copy of the rules.
 * @module @deepseek-ai/dsh-experimental-component-surface/src/component-call
 */

/** The wire tool name this package offers the model. */
export const SHOW_COMPONENT_TOOL_NAME = 'show_component'

/**
 * Command name the browser seat reports one action through. Both halves of the
 * seam live in this package, so both read this constant rather than keeping
 * their own literal copies.
 */
export const COMPONENT_ACTION_COMMAND = 'component-action'

/**
 * `source.plugin` of every notice an action produces.
 *
 * Names the seam the user is looking at — a component in the content column —
 * rather than this package's Cordis plugin name, because it is the id the chat
 * transcript prints beside the collapsed row.
 */
export const COMPONENT_ACTION_PLUGIN = 'content-component'

/**
 * Largest action document, in UTF-8 bytes, that is carried to the model.
 *
 * The command's own record is written verbatim before any handler runs, so this
 * is not a ceiling on what reaches the log — it is the point past which the
 * action is not delivered to the agent at all (see the README's Known
 * Limitations).
 *
 * Wide enough for the widest document any component here writes, which is a
 * table's select-all: {@link MAX_TABLE_ROWS} indexes, every one of them at its
 * full width, inside a frame whose four identifiers are at their own ceilings.
 * `catalog-actions.client.spec.ts` measures that document against this number,
 * so a component that widens what a gesture reports fails there rather than
 * leaving a user whose only mistake was ticking every row told their action was
 * too large.
 */
export const MAX_ACTION_PAYLOAD_BYTES = 4096

/**
 * Turns actions may open on one agent before a human message refills the
 * budget.
 *
 * A budget rather than a rate: a block whose every press wakes the agent turns
 * a user drumming on a button into an unbounded chain of turns, and the refill
 * is the human's next message, which is the only evidence the chain is still
 * wanted.
 */
export const WAKE_BUDGET = 3

/**
 * Kind key this package owns in the content column, and the `content.surface.kind`
 * slot key its browser seat claims. Written as a literal on both sides: the
 * client slot catalog is generated by scanning for literal keys.
 */
export const COMPONENT_KIND = 'component'

/** Largest accepted entry `id`, in characters. */
export const MAX_ENTRY_ID_LENGTH = 64

/** Largest accepted `title`, in characters. */
export const MAX_TITLE_LENGTH = 24

/** Largest accepted `JSON.stringify(spec)`, in UTF-8 bytes. */
export const MAX_SPEC_BYTES = 65536

/**
 * Largest accepted `spec.nodes` length.
 *
 * Also what bounds a layout tree: a layout places every node exactly once, so
 * this is both the most blocks one call draws and the most leaves that tree can
 * carry.
 */
export const MAX_NODES = 12

/**
 * Deepest accepted layout tree: the stack a spec starts with, and three levels
 * of stacks under it.
 *
 * Four levels split a panel every way twelve blocks have a reason to be split.
 * What the ceiling buys is that the deepest legal spec is a number this module
 * knows, which is what {@link MAX_SPEC_DEPTH} is measured from.
 */
export const MAX_LAYOUT_DEPTH = 4

/**
 * Largest accepted child count of one stack.
 *
 * The node ceiling, because every leaf of a layout is a node and a stack
 * carrying nothing but stacks is bounded by the leaves below it.
 */
export const MAX_LAYOUT_CHILDREN = MAX_NODES

/** Largest accepted `flex` of one placed block: the share of its stack it takes. */
export const MAX_FLEX = 12

/** Largest accepted node `id`, in characters. */
export const MAX_NODE_ID_LENGTH = 32

/** Largest accepted output `id`, in characters. */
export const MAX_OUTPUT_ID_LENGTH = 32

/** Largest accepted button `id` inside a confirmation bar, in characters. */
export const MAX_BUTTON_ID_LENGTH = 32

/** Characters an entry id, a node id, and a catalog-declared token property may use. */
export const TOKEN_CHARSET = /^[\w-]+$/

/** Model-facing wording of {@link TOKEN_CHARSET}, spliced into every refusal and description that states it. */
export const TOKEN_HINT = 'letters, digits, underscores and hyphens'

/**
 * Characters a data field name may use — a column's source field, a filter
 * attribute, a key of a row.
 *
 * Tighter than {@link TOKEN_CHARSET} at the first character, because these names
 * are spliced into a component's own property lookups rather than compared as
 * opaque ids, and a name that may start with a digit or a hyphen is one a model
 * can write to look like something else.
 */
export const FIELD_CHARSET = /^[A-Za-z_][\w-]*$/

/** Model-facing wording of {@link FIELD_CHARSET}, spliced into every refusal that states it. */
export const FIELD_HINT = 'a letter or an underscore, then letters, digits, underscores and hyphens'

/** Largest accepted data field name, in characters. */
export const MAX_FIELD_NAME_LENGTH = 64

/**
 * The cell renderers a table column may name.
 *
 * A whitelist rather than a check for a legal identifier: the value chooses code
 * that draws a cell, so a name outside this list is not a renderer this build
 * has, whatever it is spelled like. One home, because it is both the set a call
 * is refused against and the set the tightening pass falls back from.
 */
export const RELATED_COMPONENTS: readonly string[] = [
  'display_default',
  'display_yesno',
  'display_progress',
  'display_circle',
  'display_tag',
]

/** The renderer a column naming something outside {@link RELATED_COMPONENTS} is drawn with. */
export const RELATED_COMPONENT_FALLBACK = 'display_default'

/**
 * The match strategies a filter condition may name, each with the wording the
 * user reads beside it.
 *
 * The sixteen the editor draws, in its own order and with its own wording. The
 * table has to be the editor's rather than a narrower one, because a strategy
 * missing here is one the user can still pick and the host then refuses whole:
 * the person would tick a strategy the console itself offered and be told their
 * filter was not recorded.
 *
 * `NOT_BETWEEN` is the one the component library's own `matchUtil` does not
 * evaluate. It is here all the same, because this package runs no query — the
 * conditions reach the model as an account of what the user asked for, and what
 * a backend does with `NOT_BETWEEN` is that backend's answer to give.
 */
export const MATCH_OPERATORS = [
  { value: 'EQ', label: '等于' },
  { value: 'NOT_EQ', label: '不等于' },
  { value: 'IN', label: '包含' },
  { value: 'NOT_IN', label: '不包含' },
  { value: 'LIKE', label: '模糊匹配' },
  { value: 'NOT_LIKE', label: '模糊不匹配' },
  { value: 'IS_NULL', label: '空值' },
  { value: 'NOT_NULL', label: '不为空' },
  { value: 'PREFIX', label: '以***为前缀' },
  { value: 'NOT_PREFIX', label: '不以***为前缀' },
  { value: 'GREATER_THAN', label: '大于' },
  { value: 'EQ_AND_GREATER_THAN', label: '大于等于' },
  { value: 'LESS_THAN', label: '小于' },
  { value: 'LESS_AND_EQ_THAN', label: '小于等于' },
  { value: 'BETWEEN', label: '在***之间' },
  { value: 'NOT_BETWEEN', label: '不在***之间' },
] as const satisfies readonly { readonly value: string; readonly label: string }[]

/** Just the ids of {@link MATCH_OPERATORS}: the set one condition's `op` is judged against. */
export const MATCH_OPERATOR_IDS: readonly string[] = MATCH_OPERATORS.map(operator => operator.value)

/**
 * How a filter joins its conditions, as the condition editor spells the choice
 * the user makes between them.
 */
const MATCH_MODES: readonly string[] = ['AND', 'OR']

/** One restricted string property: bounded length, optionally a restricted alphabet. */
export interface StringFieldSchema {
  /** Discriminant. */
  readonly kind: 'string'
  /** Largest accepted value, in characters. */
  readonly maxLength: number
  /** Alphabet the value is restricted to; absent when any character is accepted. */
  readonly charset?: StringCharset
}

/** An alphabet restriction, together with the wording a refusal states it in. */
export interface StringCharset {
  /** Characters the whole value must match. */
  readonly allowed: RegExp
  /** Model-facing description of {@link allowed}, spliced into the refusal. */
  readonly hint: string
}

/** One property whose value must be one of a fixed set of scalars. */
export interface EnumFieldSchema {
  /** Discriminant. */
  readonly kind: 'enum'
  /** The accepted values, in the order a refusal lists them. */
  readonly values: readonly (string | number)[]
}

/**
 * One property whose value is a number inside declared bounds.
 *
 * A range rather than a set, for a quantity a component reads as a measurement:
 * a width in pixels is any number the layout can carry. A property with a
 * handful of legal values is an {@link EnumFieldSchema} instead, because a range
 * would also admit the values between them.
 */
export interface NumberFieldSchema {
  /** Discriminant. */
  readonly kind: 'number'
  /** Smallest accepted value. */
  readonly min: number
  /** Largest accepted value. */
  readonly max: number
}

/** One property whose value is `true` or `false`. */
export interface BooleanFieldSchema {
  /** Discriminant. */
  readonly kind: 'boolean'
}

/** One property whose value is a nested object of further declared properties. */
export interface ObjectFieldSchema {
  /** Discriminant. */
  readonly kind: 'object'
  /** The declared properties; anything else is refused. */
  readonly fields: PropsSchema
}

/**
 * One property whose value is an object whose keys are the caller's rather than
 * this schema's: a row of a table, keyed by the fields its columns read.
 *
 * The keys are data, so they are bounded by an alphabet, a length and a count
 * instead of being listed one by one; the values are scalars only, which is
 * what keeps a row from carrying a document nothing declared. Where an
 * {@link ObjectFieldSchema} would be a lie about who names the keys, this is
 * the honest declaration of the same JSON.
 */
export interface RecordFieldSchema {
  /** Discriminant. */
  readonly kind: 'record'
  /** What every key must be. */
  readonly key: StringFieldSchema
  /** Most keys one record may carry. */
  readonly maxKeys: number
  /** Largest accepted string value, in characters. */
  readonly maxValueLength: number
  /** Smallest accepted numeric value. */
  readonly minValue: number
  /** Largest accepted numeric value. */
  readonly maxValue: number
  /**
   * Keys of this record read as something narrower than text, by key name.
   *
   * Declared here rather than in the component's own {@link SanitizeRules}
   * because a record's keys are data: a table column named `color` is a field
   * of the caller's own records, and a component-level rule keyed by that name
   * would tighten every row's cell as well as the one configuration key that
   * really is a color.
   */
  readonly sanitize?: SanitizeRules
}

/**
 * One property whose value is a bounded list.
 *
 * An item is most often a record — a list a component draws is usually rows the
 * user can point at, and one of their properties then identifies the item — but
 * it may be any declared shape, because a reported gesture also carries lists
 * of bare values: the row numbers one selection covers.
 */
export interface ArrayFieldSchema {
  /** Discriminant. */
  readonly kind: 'array'
  /** Schema every item is measured against. */
  readonly item: PropsFieldSchema
  /** Fewest accepted items. */
  readonly minItems: number
  /** Most accepted items. */
  readonly maxItems: number
  /**
   * Item property that must be unique across the list; absent when the items
   * carry no identity.
   *
   * Present wherever an item is something the user points at, because a
   * reported gesture names the item by that property and two items sharing it
   * name neither. A list nothing reports back from — rows of a record, read and
   * not touched — declares none, and repeated values there are the data rather
   * than a mistake.
   */
  readonly uniqueBy?: string
}

/**
 * What a declared property may be.
 *
 * The union is the security boundary rather than a convenience: no member can
 * express rich text or a function body, so a model cannot write either into a
 * component's props and nothing downstream has to recognize one. Every string
 * reaches the seat as a text value, and a record's values are scalars, so a
 * caller-keyed object cannot smuggle back what the union excludes.
 *
 * Where a component needs a string read as something narrower than text — a
 * path, a color — the narrowing is a {@link SanitizeClass} declared beside the
 * schema rather than a schema member of its own, which is what keeps the
 * tightened readings a closed list instead of a spelling each component invents.
 */
export type PropsFieldSchema =
  | StringFieldSchema
  | NumberFieldSchema
  | BooleanFieldSchema
  | EnumFieldSchema
  | ObjectFieldSchema
  | RecordFieldSchema
  | ArrayFieldSchema

/** One declared property of a component. */
export interface PropsField {
  /** Whether a call must carry the property. */
  readonly required: boolean
  /** What the value must be. */
  readonly schema: PropsFieldSchema
  /**
   * Why no other block's output may stand here; absent for a property that may
   * be read from another block.
   *
   * Model-facing, and spliced into the refusal after the path it names, so a
   * call that bound the property is told what this particular property is
   * rather than that it is on a list. What makes a property one of these is
   * that something outside the drawing of the block reads it: the host, naming
   * what the user did in the block it drew, or a second property of the same
   * call the component reads it against row for row. Neither reading reaches a
   * value the page resolved — that value is in no call, and it outlives no
   * render.
   */
  readonly unbindable?: string
}

/** A component's declared properties, keyed by property name. */
export type PropsSchema = Readonly<Record<string, PropsField>>

/**
 * What a declared string is read as, where text is not a tight enough reading.
 *
 * A closed list, and every member is a value the seat hands the browser as
 * something other than text: `path` reaches an address something navigates to,
 * `color` reaches a style, `related-component` chooses which renderer draws a
 * cell. What each one accepts, and whether a value outside it is dropped or
 * falls back, is `sanitize.ts`'s.
 */
export type SanitizeClass = 'path' | 'color' | 'related-component'

/**
 * The tightened readings of one component's properties, keyed by property name.
 *
 * By name rather than by path, because a reading follows the name wherever it
 * appears: a `relatedComponent` inside a list item chooses a renderer exactly as
 * one at the top level does, and a component declaring the tighter reading for
 * one of the two would have declared it only where it remembered to.
 */
export type SanitizeRules = Readonly<Record<string, SanitizeClass>>

/**
 * What the host does with one reported action.
 *
 * Three grades and no fourth. `silent` is swallowed where it happens; `context`
 * waits in the agent's inbox and is read at its next step; `wake` opens a turn
 * of its own. The grade belongs to the action rather than to a deployment,
 * because it follows from what the gesture means — a sort order is not news, a
 * pressed confirmation is the answer the agent was waiting for — and a
 * deployment that moved it would be changing what the agent is told happened.
 */
export type ActionReport = 'silent' | 'context' | 'wake'

/**
 * Everything one action's account is built from, all of it host-side: the entry
 * as the log recorded it, the node the block was drawn from, and the payload
 * after it passed the action's declared properties.
 *
 * The seat's own text is deliberately absent. What the user pressed is named
 * from the catalog and from the spec the model itself wrote, so a page that
 * lies about its labels cannot put words in the user's mouth.
 */
export interface ComponentActionContext {
  /** The content entry the block belongs to; also what the model reuses to replace it. */
  readonly entryId: string
  /** The entry's user-facing title, as the accepted call wrote it. */
  readonly entryTitle: string
  /** The node the block was drawn from, as validation accepted it. */
  readonly node: ComponentNode
  /** The catalog entry the node names. */
  readonly component: ComponentCatalogEntry
  /** The action's payload, after it passed {@link ComponentActionDefinition.payloadSchema}. */
  readonly payload: Readonly<Record<string, unknown>>
}

/** The two accounts one reported action produces. */
export interface ComponentActionNotice {
  /**
   * What the agent is told, from the agent's own vantage: what the user did,
   * and the entry and node ids to name it by. English, like every other
   * model-facing string in this package; the labels quoted inside it are the
   * end user's own wording.
   */
  readonly text: string
  /** The one line the user reads on the collapsed transcript row. Chinese, like every other user-facing string here. */
  readonly summary: string
}

/** One action a component reports back out of a drawn block. */
export interface ComponentActionDefinition {
  /** Stable id the seat writes in the action document's `actionId`. */
  readonly id: string
  /** What the host does with it. */
  readonly report: ActionReport
  /** The only payload properties this action accepts; anything else is refused, exactly as for a component's props. */
  readonly payloadSchema: PropsSchema
  /**
   * Build the two accounts of one occurrence.
   * @param context - the entry, the node, the catalog entry, and the accepted payload.
   * @returns the accounts, or `undefined` when the payload names nothing the
   *   drawn block actually carries — a press of a button that is not on screen
   *   is reported to nobody.
   */
  readonly describe: (context: ComponentActionContext) => ComponentActionNotice | undefined
}

/**
 * One value a drawn block reports out for another block of the same call to
 * read.
 *
 * An output is not an action: an action is news the agent is told about, and an
 * output is a value that stays inside the panel. The seat holds the latest one
 * per block and hands it to whatever bound it, and nothing about it reaches the
 * log — which is what lets a selection drive a detail block without writing a
 * session event every time the user ticks a row.
 */
export interface ComponentOutput {
  /** Stable id a `$from` reference names after the dot. */
  readonly id: string
  /**
   * What the value is, written in the vocabulary a declared property uses.
   *
   * The same schema union on purpose: it is what lets the host decide, before
   * anything is drawn, whether an output can be the value of the property a
   * call bound it to.
   */
  readonly shape: PropsFieldSchema
}

/** One component a call may place. */
export interface ComponentCatalogEntry {
  /** Stable id the model writes in `spec.nodes[i].component`. */
  readonly id: string
  /** The name the end user reads. Chinese, because it is user-facing copy rather than model-facing text. */
  readonly label: string
  /** One model-facing sentence saying when the component is worth using; spliced into the tool description. */
  readonly purpose: string
  /** The only properties this component accepts. */
  readonly propsSchema: PropsSchema
  /** The only actions this component reports back; empty for a component nothing comes back from. */
  readonly actions: readonly ComponentActionDefinition[]
  /** The only outputs another block may read from this one; empty for a component nothing can be read from. */
  readonly outputs: readonly ComponentOutput[]
  /** Properties read as something narrower than text; absent when every string of this component is text. */
  readonly sanitize?: SanitizeRules
}

/** Catalog id of the confirmation bar. */
export const CONFIRM_BAR_ID = 'el.confirm-bar'

/** The confirmation bar's declared properties. */
const CONFIRM_BAR_PROPS: PropsSchema = {
  title: { required: false, schema: { kind: 'string', maxLength: 80 } },
  message: { required: false, schema: { kind: 'string', maxLength: 400 } },
  buttons: {
    required: true,
    schema: {
      kind: 'array',
      minItems: 1,
      maxItems: 5,
      uniqueBy: 'id',
      item: {
        kind: 'object',
        fields: {
          id: {
            required: true,
            schema: {
              kind: 'string',
              maxLength: MAX_BUTTON_ID_LENGTH,
              charset: { allowed: TOKEN_CHARSET, hint: TOKEN_HINT },
            },
          },
          label: { required: true, schema: { kind: 'string', maxLength: 16 } },
          tone: { required: false, schema: { kind: 'enum', values: ['primary', 'default', 'danger'] } },
        },
      },
    },
  },
}

/** Action id the confirmation bar reports a button press under. */
export const CONFIRM_BAR_PRESS_ID = 'press'

/**
 * Read one button's user-facing label out of the spec the panel is drawing.
 *
 * The cast is what validation already proved: the node reached here only
 * through the confirmation bar's own `propsSchema`, where `buttons` is a
 * required list whose every item carries a required string `id` and a required
 * string `label`.
 * @param node - the drawn node, as validation accepted it.
 * @param buttonId - the pressed button's id, as the action's payload carried it.
 * @returns the label, or `undefined` when the drawn bar carries no such button.
 */
function buttonLabel(node: ComponentNode, buttonId: unknown): string | undefined {
  const buttons = node.props['buttons'] as readonly { readonly id: string; readonly label: string }[]
  return buttons.find(button => button.id === buttonId)?.label
}

/**
 * The confirmation bar's one action.
 *
 * `wake` because a press is the whole reason the bar was placed: the agent put
 * a decision in front of the user and stopped, and the answer arriving as
 * quiet context would leave it sitting there. The payload carries the button's
 * id and nothing else — the label the notice quotes is read back out of the
 * spec, so the seat cannot report a press of "Cancel" as a press of "Delete".
 */
const CONFIRM_BAR_ACTIONS: readonly ComponentActionDefinition[] = [{
  id: CONFIRM_BAR_PRESS_ID,
  report: 'wake',
  payloadSchema: {
    buttonId: {
      required: true,
      schema: {
        kind: 'string',
        maxLength: MAX_BUTTON_ID_LENGTH,
        charset: { allowed: TOKEN_CHARSET, hint: TOKEN_HINT },
      },
    },
  },
  describe: (context) => {
    const pressed = buttonLabel(context.node, context.payload['buttonId'])
    if (pressed === undefined) return undefined
    const label = quote(pressed)
    return {
      text: `The user pressed ${label.agent} in ${place(context)}.`,
      summary: `用户在「${entryName(context)}」里点了「${label.user}」`,
    }
  },
}]

/** Catalog id of the record detail. */
export const RECORD_DETAIL_ID = 'toy.record'

/**
 * The record detail's declared properties.
 *
 * The rows are the whole component: a label and the text beside it, already
 * written out. Nothing here says where a value came from or how to format it —
 * the model sends what it wants read, and a row is drawn as the two strings it
 * carries.
 *
 * A row's label is bounded by {@link MAX_FIELD_NAME_LENGTH} rather than by a
 * number of its own, because a table's `selectionDetail` is read into this list
 * and a column with no header of its own contributes the field name it reads.
 * Two ceilings there would be a binding the catalog offers and refuses.
 */
const RECORD_DETAIL_PROPS: PropsSchema = {
  dataList: {
    required: true,
    schema: {
      kind: 'array',
      minItems: 1,
      maxItems: 60,
      item: {
        kind: 'object',
        fields: {
          label: { required: true, schema: { kind: 'string', maxLength: MAX_FIELD_NAME_LENGTH } },
          display: { required: true, schema: { kind: 'string', maxLength: 400 } },
        },
      },
    },
  },
  labelWidth: { required: false, schema: { kind: 'number', min: 40, max: 240 } },
  columnNum: { required: false, schema: { kind: 'enum', values: [1, 2, 3] } },
}

/**
 * One thing a notice states twice: once in the agent's English account, once in
 * the user's Chinese line.
 *
 * Every value a notice quotes takes this form, because each has to read
 * naturally in two places at once — as data inside an English sentence, and as
 * the words themselves inside a Chinese one.
 */
interface NoticePhrase {
  /** The wording inside the agent's account. */
  readonly agent: string
  /** The wording inside the user's line. */
  readonly user: string
}

/**
 * Characters free text is stripped of before it is read back to anyone.
 *
 * The user's line is one line in a chat row. A newline, a tab, or a
 * bidirectional override anywhere in it becomes a space rather than rearranging
 * the sentence it sits in — and every value in that sentence is free text
 * somebody wrote: the title the model gave the entry, the header it put on a
 * column, the label on a button, what a row's first cell shows, and what the
 * user typed into a filter.
 */
const NOT_ONE_LINE = /[\p{Cc}\p{Cf}]/gu

/**
 * Read one piece of free text back on a single line.
 * @param value - the text, as the spec or the payload carries it.
 * @returns the text with everything that would take it off one line replaced by a space.
 */
function plainLine(value: string): string {
  return value.replace(NOT_ONE_LINE, ' ')
}

/**
 * State one piece of free text in both accounts, as the data it is.
 *
 * Every value a notice quotes goes through here, so the two halves of one
 * sentence cannot treat their neighbouring values differently: the agent reads
 * it escaped the way JSON writes a string, so nothing inside it can end the
 * quotation it sits in, and the user reads what was written, on one line.
 * @param value - the text, as the spec or the payload carries it.
 * @returns the two wordings, the agent's already carrying its own quotation marks.
 */
function quote(value: string): NoticePhrase {
  return { agent: JSON.stringify(value), user: plainLine(value) }
}

/**
 * Name the place one gesture happened, in the wording every notice shares.
 * @param context - the entry, the node and the catalog entry the action resolved against.
 * @returns the phrase every action's account ends with, after `in `.
 */
function place({ entryId, entryTitle, node, component }: ComponentActionContext): string {
  return `content panel entry "${entryId}" (${quote(entryTitle).agent}), on the ${component.label} block "${node.id}"`
}

/**
 * Name the entry the way the user's own line names it.
 * @param context - the action's context, carrying the title the placing call wrote.
 * @returns the title on one line, for the brackets every summary puts it in.
 */
function entryName({ entryTitle }: ComponentActionContext): string {
  return plainLine(entryTitle)
}

/** One data field name, as a column, a filter attribute and a record key all declare it. */
const FIELD_NAME: StringFieldSchema = {
  kind: 'string',
  maxLength: MAX_FIELD_NAME_LENGTH,
  charset: { allowed: FIELD_CHARSET, hint: FIELD_HINT },
}

/** Widest numeric value a record may carry: every integer JSON carries exactly. */
const MAX_RECORD_NUMBER = Number.MAX_SAFE_INTEGER

/** Catalog id of the data table. */
export const TABLE_ID = 'toy.table'

/**
 * Largest accepted row count of one table.
 *
 * Every drawn row is a row the user may tick, and a select-all reports all of
 * them at once, so this ceiling and {@link MAX_SELECTED_ROWS} are one number:
 * a table wider than one selection can carry is a table whose header checkbox
 * reports nothing.
 */
export const MAX_TABLE_ROWS = 500

/** Largest accepted column count of one table. */
export const MAX_TABLE_COLUMNS = 30

/** Largest accepted custom-operation count of one table. */
export const MAX_TABLE_OPERATIONS = 5

/** Keys one table row may carry: the columns it is read through, plus the fields nothing draws. */
const MAX_ROW_KEYS = 40

/**
 * Largest accepted column header, in characters. Exported because a header
 * taken from a data backend's own dictionary is judged against it before it is
 * written into a column, and the two must be one number.
 */
export const MAX_COLUMN_ALIAS_LENGTH = 40

/** Largest accepted value inside one table row, in characters. */
const MAX_ROW_VALUE_LENGTH = 200

/** One row of a table, keyed by the fields its columns read. */
const TABLE_ROW: RecordFieldSchema = {
  kind: 'record',
  key: FIELD_NAME,
  maxKeys: MAX_ROW_KEYS,
  maxValueLength: MAX_ROW_VALUE_LENGTH,
  minValue: -MAX_RECORD_NUMBER,
  maxValue: MAX_RECORD_NUMBER,
}

/**
 * One cell renderer's configuration, handed to whichever renderer the column
 * named.
 *
 * Its `color` key reaches a style rather than a text node, which is why the
 * record declares that reading itself: the same key name in a row is a field of
 * the caller's data and stays text.
 */
const CELL_CONFIG: RecordFieldSchema = {
  kind: 'record',
  key: FIELD_NAME,
  maxKeys: 20,
  maxValueLength: 64,
  minValue: -MAX_RECORD_NUMBER,
  maxValue: MAX_RECORD_NUMBER,
  sanitize: { color: 'color' },
}

/**
 * The data table's declared properties.
 *
 * `tableConfig.gridItems` is the column list and `displayValueList` is the rows,
 * exactly as the component library's own backend scheme names them: a column
 * reads its cell out of a row by `relatedMetaAttr`, so the two halves are one
 * vocabulary rather than a mapping this package invents.
 */
const TABLE_PROPS: PropsSchema = {
  tableConfig: {
    required: true,
    schema: {
      kind: 'object',
      fields: {
        gridItems: {
          required: true,
          schema: {
            kind: 'array',
            minItems: 1,
            maxItems: MAX_TABLE_COLUMNS,
            uniqueBy: 'relatedMetaAttr',
            item: {
              kind: 'object',
              fields: {
                relatedMetaAttr: { required: true, schema: FIELD_NAME },
                alias: { required: false, schema: { kind: 'string', maxLength: MAX_COLUMN_ALIAS_LENGTH } },
                isShow: { required: false, schema: { kind: 'boolean' } },
                isSortable: { required: false, schema: { kind: 'boolean' } },
                relatedComponent: { required: false, schema: { kind: 'enum', values: RELATED_COMPONENTS } },
                relatedComponentObj: { required: false, schema: CELL_CONFIG },
              },
            },
          },
        },
      },
    },
  },
  displayValueList: {
    required: true,
    schema: { kind: 'array', minItems: 1, maxItems: MAX_TABLE_ROWS, item: TABLE_ROW },
    unbindable: 'every gesture in this table is reported to you by reading these rows back out of the call that '
      + 'wrote them, and a value another block supplies is not in that call.',
  },
  rawValueList: {
    required: false,
    schema: { kind: 'array', minItems: 1, maxItems: MAX_TABLE_ROWS, item: TABLE_ROW },
    unbindable: 'it stands behind the drawn rows one for one, and the drawn rows are written out by the call.',
  },
  selectMode: { required: false, schema: { kind: 'enum', values: ['checkbox', 'radio'] } },
  isNameClick: { required: false, schema: { kind: 'boolean' } },
  tableSortable: { required: false, schema: { kind: 'boolean' } },
  customOperations: {
    required: false,
    schema: {
      kind: 'array',
      minItems: 1,
      maxItems: MAX_TABLE_OPERATIONS,
      uniqueBy: 'key',
      item: {
        kind: 'object',
        fields: {
          key: {
            required: true,
            schema: {
              kind: 'string',
              maxLength: MAX_BUTTON_ID_LENGTH,
              charset: { allowed: TOKEN_CHARSET, hint: TOKEN_HINT },
            },
          },
          label: { required: true, schema: { kind: 'string', maxLength: 20 } },
        },
      },
    },
  },
  operationColumnWidth: { required: false, schema: { kind: 'number', min: 60, max: 400 } },
}

/** Action id the table reports a change of selection under. */
export const TABLE_SELECT_ID = 'select'

/**
 * Action id the table reports an opened row under.
 *
 * Reported only by a table whose call asked for openable rows — `isNameClick` —
 * and then for a click anywhere in the row, which is where the component's own
 * cell click is bound. A table that asked for none reports nothing when a cell
 * is clicked, because on such a table a click opens nothing.
 */
export const TABLE_ROW_CLICK_ID = 'row-click'

/** Action id the table reports a change of sort order under. */
export const TABLE_SORT_ID = 'sort'

/** Action id the table reports a press of a custom operation under. */
export const TABLE_OPERATION_ID = 'operation'

/**
 * Rows one reported selection may carry: every row the table drew.
 *
 * Not a ceiling of its own. The table's header checkbox ticks every drawn row
 * in one gesture, and a number below {@link MAX_TABLE_ROWS} would make that one
 * gesture unreportable on a full table — with nothing on screen saying so,
 * because a selection is `context` and leaves the block no state to draw. What
 * bounds the document instead is {@link MAX_ACTION_PAYLOAD_BYTES}, which is set
 * wide enough to carry this.
 */
export const MAX_SELECTED_ROWS = MAX_TABLE_ROWS

/** Rows one notice names before it stops naming them and counts the rest. */
const MAX_NAMED_ROWS = 5

/** One row index, as every action that names a row declares it. */
const ROW_INDEX: NumberFieldSchema = { kind: 'number', min: 0, max: MAX_TABLE_ROWS - 1 }

/** One declared column, as validation accepted it. */
interface TableColumn {
  /** The row field this column reads its cell out of. */
  readonly relatedMetaAttr: string
  /** The column header, where the call wrote one. */
  readonly alias?: string
  /** Whether the column is drawn; a column the call hid carries `false`. */
  readonly isShow?: boolean
}

/** One declared custom operation, as validation accepted it. */
interface TableOperation {
  /** The id a press reports. */
  readonly key: string
  /** The button's user-facing text. */
  readonly label: string
}

/** One row a reported index resolved to. */
interface DrawnRow {
  /** The row itself, as the call wrote it. */
  readonly row: Readonly<Record<string, unknown>>
  /** Its position in the drawn list. */
  readonly index: number
}

/**
 * The columns one table block draws — the ones the user can see.
 *
 * A column the call hid is left out, because every notice built from this list
 * names something the user is looking at: a hidden column's header is not a
 * column they sorted, and its cell is not what a row shows. `isShow` is the
 * component's own reading, so only an explicit `false` hides a column.
 *
 * The cast is what validation already proved: `tableConfig` is required, its
 * `gridItems` is a required list of at least one item, and every item carries a
 * required `relatedMetaAttr` string.
 * @param node - the drawn node, as validation accepted it.
 * @returns the drawn columns, in the order the call wrote them; empty where the call hid every one.
 */
function tableColumns(node: ComponentNode): readonly TableColumn[] {
  const config = node.props['tableConfig'] as { readonly gridItems: readonly [TableColumn, ...TableColumn[]] }
  return config.gridItems.filter(column => column.isShow !== false)
}

/**
 * The rows one table block draws.
 * @param node - the drawn node, as validation accepted it.
 * @returns the rows, in the order the call wrote them.
 */
function tableRows(node: ComponentNode): readonly Readonly<Record<string, unknown>>[] {
  return node.props['displayValueList'] as readonly Readonly<Record<string, unknown>>[]
}

/**
 * Resolve one reported row index against the rows the block actually drew.
 * @param node - the drawn node.
 * @param index - the reported index, however malformed.
 * @returns the row and its position, or `undefined` when the block drew no such row.
 */
function drawnRow(node: ComponentNode, index: unknown): DrawnRow | undefined {
  if (typeof index !== 'number' || !Number.isInteger(index)) return undefined
  const row = tableRows(node)[index]
  return row === undefined ? undefined : { row, index }
}

/**
 * Read what one row shows in the first column the table draws.
 * @param node - the drawn node.
 * @param row - the row.
 * @returns the cell as text, or `undefined` where the table draws no column or that column shows nothing readable.
 */
function firstColumnValue(node: ComponentNode, row: Readonly<Record<string, unknown>>): string | undefined {
  const column = tableColumns(node)[0]
  if (column === undefined) return undefined
  const value = row[column.relatedMetaAttr]
  if (typeof value === 'number') return String(value)
  if (typeof value === 'string' && value.length > 0) return value
  return undefined
}

/**
 * Name one drawn row the way the user sees it: by what its first column shows,
 * and by its position where that column shows nothing.
 * @param node - the drawn node.
 * @param drawn - the resolved row.
 * @returns the two namings.
 */
function nameRow(node: ComponentNode, drawn: DrawnRow): NoticePhrase {
  const label = firstColumnValue(node, drawn.row)
  if (label === undefined) return { agent: `#${drawn.index + 1}`, user: `第 ${drawn.index + 1} 行` }
  return quote(label)
}

/**
 * Name every row one selection reported, in the order it reported them.
 * @param node - the drawn node.
 * @param indexes - the reported indexes, however malformed.
 * @returns the names, or `undefined` when any index names a row the block did not draw.
 */
function nameRows(node: ComponentNode, indexes: readonly unknown[]): readonly NoticePhrase[] | undefined {
  const names: NoticePhrase[] = []
  for (const index of indexes) {
    const drawn = drawnRow(node, index)
    if (drawn === undefined) return undefined
    names.push(nameRow(node, drawn))
  }
  return names
}

/**
 * The four gestures a table reports.
 *
 * The grades follow what each gesture means rather than how loud it is. A
 * selection and an opened row are `context`: they change what the agent should
 * be reasoning about without answering anything it stopped for. A
 * sort is `silent`, because the order rows are drawn in is the user arranging
 * their own screen. A custom operation is `wake`, because the model put that
 * button there to be pressed and the press is the answer.
 *
 * Every notice is built from the entry's own spec: the rows are named by what
 * the first drawn column shows, a column by the header the call wrote, and an
 * operation by its declared label. An index outside the drawn rows, an
 * operation the table does not carry, and a column the call hid resolve to
 * nothing at all rather than to a notice naming something the user never saw.
 */
const TABLE_ACTIONS: readonly ComponentActionDefinition[] = [
  {
    id: TABLE_SELECT_ID,
    report: 'context',
    payloadSchema: {
      rowIndexes: {
        required: true,
        schema: { kind: 'array', minItems: 0, maxItems: MAX_SELECTED_ROWS, item: ROW_INDEX },
      },
    },
    describe: (context) => {
      const indexes = context.payload['rowIndexes']
      if (!Array.isArray(indexes)) return undefined
      const names = nameRows(context.node, indexes)
      if (names === undefined) return undefined
      const where = place(context)
      if (names.length === 0) {
        return {
          text: `The user cleared the selection in ${where}.`,
          summary: `用户在「${entryName(context)}」里取消了选择`,
        }
      }
      const shown = names.slice(0, MAX_NAMED_ROWS)
      const hidden = names.length - shown.length
      return {
        text: `The user selected ${names.length} row${names.length === 1 ? '' : 's'} in ${where}: `
          + `${shown.map(name => name.agent).join(', ')}${hidden === 0 ? '' : ` and ${hidden} more`}.`,
        summary: `用户在「${entryName(context)}」里选中了 ${names.length} 行：`
          + `${shown.map(name => name.user).join('、')}${hidden === 0 ? '' : ` 等 ${names.length} 行`}`,
      }
    },
  },
  {
    id: TABLE_ROW_CLICK_ID,
    report: 'context',
    payloadSchema: { rowIndex: { required: true, schema: ROW_INDEX } },
    describe: (context) => {
      const drawn = drawnRow(context.node, context.payload['rowIndex'])
      if (drawn === undefined) return undefined
      const name = nameRow(context.node, drawn)
      return {
        text: `The user clicked row ${name.agent} in ${place(context)}.`,
        summary: `用户在「${entryName(context)}」里点了「${name.user}」`,
      }
    },
  },
  {
    id: TABLE_SORT_ID,
    report: 'silent',
    payloadSchema: {
      prop: { required: true, schema: FIELD_NAME },
      order: { required: true, schema: { kind: 'enum', values: ['asc', 'desc', 'none'] } },
    },
    describe: (context) => {
      const column = tableColumns(context.node).find(one => one.relatedMetaAttr === context.payload['prop'])
      if (column === undefined) return undefined
      const order = context.payload['order']
      const where = place(context)
      if (order === 'none') {
        return {
          text: `The user cleared the sort in ${where}.`,
          summary: `用户取消了「${entryName(context)}」的排序`,
        }
      }
      if (order !== 'asc' && order !== 'desc') return undefined
      const header = quote(column.alias ?? column.relatedMetaAttr)
      return {
        text: `The user sorted by ${header.agent}, ${order === 'asc' ? 'ascending' : 'descending'}, in ${where}.`,
        summary: `用户把「${entryName(context)}」按「${header.user}」${order === 'asc' ? '升序' : '降序'}排列`,
      }
    },
  },
  {
    id: TABLE_OPERATION_ID,
    report: 'wake',
    payloadSchema: {
      opId: {
        required: true,
        schema: {
          kind: 'string',
          maxLength: MAX_BUTTON_ID_LENGTH,
          charset: { allowed: TOKEN_CHARSET, hint: TOKEN_HINT },
        },
      },
      rowIndex: { required: true, schema: ROW_INDEX },
    },
    describe: (context) => {
      const operations = context.node.props['customOperations'] as readonly TableOperation[] | undefined
      const operation = operations?.find(one => one.key === context.payload['opId'])
      if (operation === undefined) return undefined
      const drawn = drawnRow(context.node, context.payload['rowIndex'])
      if (drawn === undefined) return undefined
      const name = nameRow(context.node, drawn)
      const label = quote(operation.label)
      return {
        text: `The user pressed ${label.agent} on row ${name.agent} in ${place(context)}.`,
        summary: `用户在「${entryName(context)}」里对「${name.user}」点了「${label.user}」`,
      }
    },
  },
]

/** Output id the table reports the first ticked row, read as label-and-value rows, under. */
export const TABLE_SELECTION_DETAIL_OUTPUT = 'selectionDetail'

/**
 * The one value another block may read out of a table.
 *
 * `selectionDetail` is the first ticked row already read into the
 * label-and-value rows a record detail draws: the label is the column's own
 * header, or the field it reads where the call gave it no header, and the value
 * is what that row shows in it. The translation is the seat's, and it is
 * declared here because "the ticked row, laid out" is the one reading that
 * makes the pair of blocks a model actually places — a table over a detail of
 * whatever is ticked — expressible without a second component.
 *
 * The ticked rows in the form the call wrote them are not offered beside it.
 * Nothing in this catalog declares a property that takes rows — a table's own
 * two row properties are {@link PropsField.unbindable}, because a table's rows
 * are what its gestures are reported back against — so an output carrying them
 * would be one every binding to it is refused. It is declared again with the
 * component that takes rows as an input.
 */
const TABLE_OUTPUTS: readonly ComponentOutput[] = [
  {
    id: TABLE_SELECTION_DETAIL_OUTPUT,
    shape: {
      kind: 'array',
      minItems: 0,
      maxItems: MAX_TABLE_COLUMNS,
      item: {
        kind: 'object',
        fields: {
          label: { required: true, schema: { kind: 'string', maxLength: MAX_FIELD_NAME_LENGTH } },
          display: { required: true, schema: { kind: 'string', maxLength: MAX_ROW_VALUE_LENGTH } },
        },
      },
    },
  },
]

/** Catalog id of the filter bar. */
export const FILTER_BAR_ID = 'el.filter-bar'

/** Largest accepted attribute count of one filter bar. */
export const MAX_FILTER_ATTRIBUTES = 40

/** Largest accepted condition count of one submitted filter. */
export const MAX_FILTER_CONDITIONS = 10

/**
 * Largest condition count one unsubmitted edit may report.
 *
 * Deliberately not {@link MAX_FILTER_CONDITIONS}. The condition editor adds a
 * row whenever the user presses its own add button and stops at nothing, and an
 * edit reports only how many rows are standing. Bounding that report by what a
 * submitted filter may carry would answer every edit past the tenth row with
 * the sentence saying the gesture was not recorded — once per keystroke the
 * user commits, for a report they never asked to send. A count is one integer
 * whatever it holds, so nothing about the document argues for the tighter
 * number; what a filter over the ceiling cannot do is be submitted, and that is
 * answered at the submit.
 */
export const MAX_EDITED_CONDITIONS = 1000

/** Largest accepted condition value, in characters. */
export const MAX_CONDITION_VALUE_LENGTH = 200

/**
 * The conditions one submitted filter carries, as the gesture reports them to
 * the agent.
 *
 * The bar publishes nothing beside it: no component in this catalog declares a
 * property that takes a condition list, so an output carrying one would be an
 * output every binding to it is refused. It is declared with the component that
 * takes conditions as an input.
 */
const FILTER_CONDITIONS: ArrayFieldSchema = {
  kind: 'array',
  minItems: 1,
  maxItems: MAX_FILTER_CONDITIONS,
  item: {
    kind: 'object',
    fields: {
      key: { required: true, schema: FIELD_NAME },
      op: { required: true, schema: { kind: 'enum', values: MATCH_OPERATOR_IDS } },
      value: { required: true, schema: { kind: 'string', maxLength: MAX_CONDITION_VALUE_LENGTH } },
    },
  },
}

/**
 * The value kinds a filter attribute may declare.
 *
 * The seven the value control reads. Everything else the component library's own
 * attribute metadata can say — the kinds that make the control fetch its options
 * from a backend — is absent, because those controls reach a service this
 * package has none of and would draw a disabled input.
 */
const FILTER_DATA_TYPES: readonly string[] = ['string', 'date', 'datetosecond', 'integer', 'long', 'float', 'double']

/**
 * The filter bar's declared properties.
 *
 * `relatedMeta` and `metaConfig.attributes` are the model's description of what
 * is being filtered; nothing is fetched, so a bar draws exactly the attributes
 * the call listed. `attrEqEnums` narrows the match strategies on offer, and a
 * call that omits it offers all sixteen — every one the editor draws.
 */
const FILTER_BAR_PROPS: PropsSchema = {
  relatedMeta: { required: true, schema: FIELD_NAME },
  metaConfig: {
    required: true,
    schema: {
      kind: 'object',
      fields: {
        attributes: {
          required: true,
          schema: {
            kind: 'array',
            minItems: 1,
            maxItems: MAX_FILTER_ATTRIBUTES,
            uniqueBy: 'attributeEnName',
            item: {
              kind: 'object',
              fields: {
                attributeEnName: { required: true, schema: FIELD_NAME },
                alias: { required: true, schema: { kind: 'string', maxLength: 40 } },
                dataType: { required: false, schema: { kind: 'enum', values: FILTER_DATA_TYPES } },
              },
            },
          },
        },
      },
    },
  },
  attrEqEnums: {
    required: false,
    schema: {
      kind: 'array',
      minItems: 1,
      maxItems: MATCH_OPERATORS.length,
      uniqueBy: 'value',
      item: {
        kind: 'object',
        fields: {
          value: { required: true, schema: { kind: 'enum', values: MATCH_OPERATOR_IDS } },
          label: { required: true, schema: { kind: 'string', maxLength: 20 } },
        },
      },
    },
  },
  confStyle: {
    required: false,
    schema: {
      kind: 'object',
      fields: {
        gutter: { required: false, schema: { kind: 'number', min: 0, max: 100 } },
        showMatchMode: { required: false, schema: { kind: 'boolean' } },
      },
    },
  },
}

/** Action id the filter bar reports a submitted filter under. */
export const FILTER_SUBMIT_ID = 'submit'

/** Action id the filter bar reports an unsubmitted edit under. */
export const FILTER_CHANGE_ID = 'change'

/** One match strategy a filter bar offers, as the call declared it or as the default table carries it. */
interface FilterOperator {
  /** The id a condition's `op` carries. */
  readonly value: string
  /** The strategy's user-facing text. */
  readonly label: string
}

/** One declared filter attribute, as validation accepted it. */
interface FilterAttribute {
  /** The field name a condition's `key` carries. */
  readonly attributeEnName: string
  /** The attribute's user-facing text. */
  readonly alias: string
}

/**
 * The attributes one filter block offers.
 *
 * The cast is what validation proved: `metaConfig` is required and its
 * `attributes` is a required list whose items each carry a required
 * `attributeEnName` and a required `alias`.
 * @param node - the drawn node.
 * @returns the attributes, in the order the call wrote them.
 */
function filterAttributes(node: ComponentNode): readonly FilterAttribute[] {
  const config = node.props['metaConfig'] as { readonly attributes: readonly FilterAttribute[] }
  return config.attributes
}

/**
 * The match strategies one filter block offers.
 * @param node - the drawn node.
 * @returns the strategies the call declared, or the whole default table where it declared none.
 */
function filterOperators(node: ComponentNode): readonly FilterOperator[] {
  return (node.props['attrEqEnums'] as readonly FilterOperator[] | undefined) ?? MATCH_OPERATORS
}

/**
 * State the user's choice between the two match modes.
 *
 * The wording is written here rather than read off the payload: what the wire
 * carries is one of two ids the schema admits, and the sentence around it is
 * this package's.
 * @param mode - the reported mode, as the payload carried it.
 * @returns the two wordings, or `undefined` where the bar offered no choice and the payload carries none.
 */
function matchModeWording(mode: unknown): NoticePhrase | undefined {
  switch (mode) {
    case 'AND': return { agent: 'all of', user: '同时满足' }
    case 'OR': return { agent: 'any of', user: '满足其一' }
    default: return undefined
  }
}

/**
 * State one submitted condition in both languages.
 * @param node - the drawn node.
 * @param condition - one condition, as the payload carried it.
 * @returns the two statements, or `undefined` when the condition names something the bar does not offer.
 */
function stateCondition(node: ComponentNode, condition: unknown): NoticePhrase | undefined {
  const record = condition as Readonly<Record<string, unknown>>
  const attribute = filterAttributes(node).find(one => one.attributeEnName === record['key'])
  if (attribute === undefined) return undefined
  const operator = filterOperators(node).find(one => one.value === record['op'])
  if (operator === undefined) return undefined
  const value = record['value']
  if (typeof value !== 'string') return undefined
  // The attribute name and the strategy wording sit outside the quotation the
  // value is written into, so they are read back on one line rather than as
  // data: what they must not do is take the sentence off its line.
  const named = `${plainLine(attribute.alias)} ${plainLine(operator.label)}`
  const typed = quote(value)
  return {
    agent: `${named} ${typed.agent}`,
    user: `${named} “${typed.user}”`,
  }
}

/**
 * The two gestures a filter bar reports.
 *
 * A submitted filter is `wake`: the bar was placed to be answered, and the
 * answer is what the model needs before it can fetch anything. An unsubmitted
 * edit is `silent` — the editor reports one every time the user commits an
 * edit, which is each time they pick an attribute, pick a strategy, or leave a
 * value box they were typing in, and a model told about a filter still being
 * built would be answering a question nobody has asked yet.
 *
 * The attribute names, the strategy wording and the match mode in a notice come
 * from the spec the model wrote and from this package. The condition values do
 * not: they are what the user typed. The agent's account quotes them as JSON
 * writes a string, so nothing in a value can end the quotation it sits in; the
 * user's line reads them back as they wrote them, on one line.
 */
const FILTER_BAR_ACTIONS: readonly ComponentActionDefinition[] = [
  {
    id: FILTER_SUBMIT_ID,
    report: 'wake',
    payloadSchema: {
      conditions: { required: true, schema: FILTER_CONDITIONS },
      matchMode: { required: false, schema: { kind: 'enum', values: MATCH_MODES } },
    },
    describe: (context) => {
      const conditions = context.payload['conditions']
      if (!Array.isArray(conditions) || conditions.length === 0) return undefined
      const stated: NoticePhrase[] = []
      for (const condition of conditions) {
        const one = stateCondition(context.node, condition)
        if (one === undefined) return undefined
        stated.push(one)
      }
      const mode = matchModeWording(context.payload['matchMode'])
      return {
        text: `The user submitted a filter in ${place(context)}${mode === undefined ? '' : `, matching ${mode.agent}`}`
          + `: ${stated.map(one => one.agent).join('; ')}.`,
        summary: `用户提交了筛选条件${mode === undefined ? '' : `（${mode.user}）`}`
          + `：${stated.map(one => one.user).join('；')}`,
      }
    },
  },
  {
    id: FILTER_CHANGE_ID,
    report: 'silent',
    payloadSchema: {
      count: { required: true, schema: { kind: 'number', min: 0, max: MAX_EDITED_CONDITIONS } },
    },
    describe: (context) => {
      const count = context.payload['count']
      if (typeof count !== 'number') return undefined
      return {
        text: `The user is editing the filter in ${place(context)}: ${count} condition${count === 1 ? '' : 's'} so far.`,
        summary: `用户正在改「${entryName(context)}」的筛选条件（${count} 条）`,
      }
    },
  },
]

/** Catalog id of the metric ball. */
export const METRIC_ID = 'el.metric'

/**
 * The metric ball's declared properties.
 *
 * One number and the word beside it. The three colors reach a style rather than
 * a text node, so each is declared as a color and read as one.
 */
const METRIC_PROPS: PropsSchema = {
  size: { required: false, schema: { kind: 'number', min: 40, max: 400 } },
  process: { required: true, schema: { kind: 'number', min: 0, max: 100 } },
  text: { required: false, schema: { kind: 'string', maxLength: 20 } },
  background: { required: false, schema: { kind: 'string', maxLength: 32 } },
  borderColor: { required: false, schema: { kind: 'string', maxLength: 32 } },
  pointColor: { required: false, schema: { kind: 'string', maxLength: 32 } },
  isPointShow: { required: false, schema: { kind: 'boolean' } },
}

/**
 * Every component a call may place.
 *
 * A static table rather than a registry service, because one package owns every
 * entry: the seat that draws a kind and the schema that admits it ship
 * together. `as const` is what keeps the ids literal, so {@link CatalogId} is
 * derived from this table instead of restated beside it, and the seat's
 * `satisfies Record<CatalogId, ComponentRenderer>` turns "a catalog entry with
 * no renderer" into a compile error rather than a blank block at runtime.
 * Replace it with a registered seam when a package this one does not own needs
 * to contribute a component.
 */
export const COMPONENT_CATALOG = [
  {
    id: CONFIRM_BAR_ID,
    label: '确认条',
    purpose: 'A short prompt above a row of buttons, for putting one decision in front of the user.',
    propsSchema: CONFIRM_BAR_PROPS,
    actions: CONFIRM_BAR_ACTIONS,
    outputs: [],
  },
  {
    id: RECORD_DETAIL_ID,
    label: '记录详情',
    purpose: 'One record laid out as label-and-value pairs, for putting the details of a single thing in front of the user.',
    propsSchema: RECORD_DETAIL_PROPS,
    actions: [],
    outputs: [],
  },
  {
    id: TABLE_ID,
    label: '数据表',
    purpose: 'Rows and columns the user can tick, open, sort and act on, for putting a list of things in front of the user.',
    propsSchema: TABLE_PROPS,
    actions: TABLE_ACTIONS,
    outputs: TABLE_OUTPUTS,
    sanitize: { relatedComponent: 'related-component' },
  },
  {
    id: FILTER_BAR_ID,
    label: '筛选条件',
    purpose: 'A row of conditions the user edits and submits back to you, for agreeing on what to look for before you look.',
    propsSchema: FILTER_BAR_PROPS,
    actions: FILTER_BAR_ACTIONS,
    outputs: [],
  },
  {
    id: METRIC_ID,
    label: '指标球',
    purpose: 'One measurement drawn as a filling ball, for putting a single number in front of the user.',
    propsSchema: METRIC_PROPS,
    actions: [],
    outputs: [],
    sanitize: { background: 'color', borderColor: 'color', pointColor: 'color' },
  },
] as const satisfies readonly ComponentCatalogEntry[]

/**
 * Every id {@link COMPONENT_CATALOG} declares, as a union.
 *
 * Derived from the table rather than written beside it: adding a component
 * widens this union in the same edit, which is what makes the seat's renderer
 * table fail to compile until that component has a renderer.
 */
export type CatalogId = (typeof COMPONENT_CATALOG)[number]['id']

/** Levels a spec spends before a declared property's value: the spec object, `nodes`, one node, and its `props`. */
const SPEC_FRAME_DEPTH = 4

/**
 * Levels of nesting one declared property's value adds under `props`.
 * @param field - the declared property.
 * @returns object levels the deepest legal value of this property occupies.
 */
function fieldDepth(field: PropsFieldSchema): number {
  switch (field.kind) {
    case 'string':
    case 'number':
    case 'boolean':
    case 'enum': return 0
    case 'record': return 1
    case 'object': return 1 + schemaDepth(field.fields)
    case 'array': return 1 + fieldDepth(field.item)
    /* v8 ignore start -- PropsFieldSchema is closed and every variant returns above. */
    default: {
      // Not `assertNever` from dsh-llm, for the reason validate.ts states at its
      // own exhaustiveness check: this module is loaded by the browser seat.
      const unhandled: never = field
      throw new Error(`component-surface: unhandled props schema ${JSON.stringify(unhandled)}`)
    }
    /* v8 ignore stop */
  }
}

/**
 * Levels of nesting the deepest declared property of one schema adds under `props`.
 * @param schema - the declared properties.
 * @returns object levels the deepest legal record of this schema occupies below its own level.
 */
function schemaDepth(schema: PropsSchema): number {
  return Object.values(schema).reduce((deepest, field) => Math.max(deepest, fieldDepth(field.schema)), 0)
}

/**
 * Deepest spec nesting one catalog's declared properties make legal, counting
 * the spec object itself as level one.
 *
 * The ceiling is measured off the catalog rather than written down, so the
 * documents a component declares as legal and the depth a spec is refused at
 * cannot drift apart: a component declaring a nested property widens the
 * ceiling by exactly what that property needs. The layout tree is the spec's
 * other deep document and is measured separately, in {@link MAX_SPEC_DEPTH}.
 * @param catalog - the components a call may place.
 * @returns levels the deepest legal node of that catalog occupies.
 */
export function maxSpecDepthOf(catalog: readonly ComponentCatalogEntry[]): number {
  return SPEC_FRAME_DEPTH + catalog.reduce((deepest, entry) => Math.max(deepest, schemaDepth(entry.propsSchema)), 0)
}

/** Levels a spec spends before a layout's own children: the spec object, and the stack it starts with. */
const LAYOUT_FRAME_DEPTH = 2

/** Levels one level of the layout costs: a stack's `children` list, and the child inside it. */
const LAYOUT_LEVEL_DEPTH = 2

/**
 * Deepest accepted nesting inside `spec` for this deployment's catalog.
 *
 * The deeper of the two documents a spec carries — a node's properties, and the
 * layout tree over those nodes — plus one layout level of slack. The slack is
 * what lets a layout that opens one stack too many be refused at the stack that
 * opened it, rather than answered with a sentence about how deep `spec` may
 * nest, which names nothing the model can act on. Anything past this is
 * malformed regardless of which component it names, and refusing it before
 * anything else bounds the work every later walk does — the byte measurement
 * included, which is why the depth walk is the one that stops at a ceiling by
 * construction.
 */
export const MAX_SPEC_DEPTH = Math.max(
  maxSpecDepthOf(COMPONENT_CATALOG),
  LAYOUT_FRAME_DEPTH + LAYOUT_LEVEL_DEPTH * (MAX_LAYOUT_DEPTH + 1),
)

/**
 * Look one action up on the component that declares it.
 * @param component - the catalog entry the drawn node names.
 * @param actionId - the `actionId` an action document carried, however malformed.
 * @returns the action, or `undefined` when that component reports no such action.
 */
export function catalogAction(component: ComponentCatalogEntry, actionId: unknown): ComponentActionDefinition | undefined {
  return component.actions.find(action => action.id === actionId)
}

/**
 * Look one component up by the id a call named.
 * @param id - the `component` value, however malformed.
 * @returns the catalog entry, or `undefined` when the deployment has no such component.
 */
export function catalogEntry(id: unknown): ComponentCatalogEntry | undefined {
  return COMPONENT_CATALOG.find(entry => entry.id === id)
}

/**
 * Look one output up on the component that declares it.
 * @param component - the catalog entry the source node names.
 * @param outputId - the name a `$from` reference gave, however malformed.
 * @returns the output, or `undefined` when that component reports no such value.
 */
export function catalogOutput(component: ComponentCatalogEntry, outputId: unknown): ComponentOutput | undefined {
  return component.outputs.find(output => output.id === outputId)
}

/**
 * Whether one reported gesture is the answer its block was placed for — the
 * gesture the block draws a line about and refuses a second of.
 *
 * A `wake` is that gesture and nothing else is. The other two grades are the
 * user working rather than answering: ticking rows, cycling a sort, typing into
 * a filter that has not been submitted. A block whose every gesture claimed the
 * cell would say the conversation has a sort order, and — because a claimed
 * cell is also what stops a second answer — would kill its own submit button
 * the moment the user edited anything.
 *
 * Read off the catalog rather than off the document, so the browser seat and
 * the session fold decide it the same way from the same table.
 * @param componentId - the `componentId` an action document carried, however malformed.
 * @param actionId - the `actionId` it carried, however malformed.
 * @returns true when that component declares that action as a `wake`.
 */
export function answersBlock(componentId: unknown, actionId: unknown): boolean {
  const component = catalogEntry(componentId)
  if (component === undefined) return false
  return catalogAction(component, actionId)?.report === 'wake'
}

/**
 * How a record whose keys are the caller's own is written in a property line.
 *
 * The keys cannot be listed, because they are the model's to choose; what the
 * line has to say is that they are field names and that each one carries a
 * scalar.
 */
const RECORD_HINT = '<field>: text|number|boolean'

/**
 * How each tightened reading is stated to the model, as the suffix of the
 * property that declares it.
 *
 * A reading is enforced by `sanitize.ts`, which drops the value it refuses
 * rather than refusing the call, so a model not told the notation writes one
 * that disappears and is never told why. Each wording is the notation that
 * module accepts.
 */
const SANITIZE_HINTS: Readonly<Record<SanitizeClass, string>> = {
  path: '/same-origin-path',
  color: '#RGB|#RRGGBB|rgb()|rgba()',
  'related-component': RELATED_COMPONENTS.join('|'),
}

/**
 * Render one object whose keys are the caller's own.
 *
 * The keys are the model's to choose, so what the line states is the bound —
 * field names carrying scalars — followed by the keys the record reads as
 * something narrower than text, which are the ones whose spelling matters. Each
 * of those carries the `?` a property line gives an optional property, in the
 * same notation and for the same reason: no key of such a record is required.
 * @param schema - the declared record.
 * @returns the contents of its braces.
 */
function describeRecord(schema: RecordFieldSchema): string {
  const readings = Object.entries(schema.sanitize ?? {}).map(([key, reading]) => `${key}?: ${SANITIZE_HINTS[reading]}`)
  return [RECORD_HINT, ...readings].join(', ')
}

/**
 * Name one value inside a list, as it appears between the list's brackets.
 *
 * An item carries no property name of its own, so a component's readings are
 * matched against the properties below it rather than against the item.
 * @param schema - the declared item.
 * @param rules - the component's tightened readings, matched by property name at every level.
 * @returns the item's own rendering, with no bounds of its own.
 */
function describeItem(schema: PropsFieldSchema, rules: SanitizeRules | undefined): string {
  switch (schema.kind) {
    case 'string': return 'text'
    case 'number': return 'number'
    case 'boolean': return 'true|false'
    case 'enum': return schema.values.join('|')
    case 'record': return `{${describeRecord(schema)}}`
    case 'object': return `{${describeProps(schema.fields, rules)}}`
    case 'array': return `[${describeItem(schema.item, rules)}]`
    /* v8 ignore start -- PropsFieldSchema is closed and every variant returns above. */
    default: {
      const unhandled: never = schema
      throw new Error(`component-surface: unhandled props schema ${JSON.stringify(unhandled)}`)
    }
    /* v8 ignore stop */
  }
}

/**
 * Render what one declared property accepts, as the suffix of its name.
 *
 * Alphabets and string lengths are left out on purpose: a refusal states the one
 * the call broke, and stating all of them would cost every request the text of a
 * rule the model mostly keeps anyway. What the model cannot recover from a
 * refusal is the structure — which properties exist, which are lists, and what
 * an item of a list carries — so that is what the suffix carries, all the way
 * down. A nested list stated only as a name is a list whose item properties cost
 * one refused call each to discover. A string the component reads as something
 * narrower does state its notation, because that reading is enforced by a pass
 * that drops the value instead of refusing the call.
 * @param field - the declared property.
 * @param rules - the component's tightened readings, matched by property name at every level.
 * @param reading - this property's own tightened reading, where it declares one.
 * @returns the suffix, empty for a plain string that declares no reading.
 */
function describeField(
  field: PropsFieldSchema,
  rules: SanitizeRules | undefined,
  reading: SanitizeClass | undefined,
): string {
  switch (field.kind) {
    case 'string': return reading === undefined ? '' : ` (${SANITIZE_HINTS[reading]})`
    case 'number': return ` (${field.min}–${field.max})`
    case 'boolean': return ' (true|false)'
    case 'enum': return ` (${field.values.join('|')})`
    case 'record': return `{${describeRecord(field)}}`
    case 'object': return `{${describeProps(field.fields, rules)}}`
    case 'array': return `[${describeItem(field.item, rules)}] (${field.minItems}–${field.maxItems})`
    /* v8 ignore start -- PropsFieldSchema is closed and every variant returns above. */
    default: {
      // Not `assertNever` from dsh-llm, for the reason validate.ts states at its
      // own exhaustiveness check: this module is loaded by the browser seat.
      const unhandled: never = field
      throw new Error(`component-surface: unhandled props schema ${JSON.stringify(unhandled)}`)
    }
    /* v8 ignore stop */
  }
}

/**
 * Render one set of declared properties: a component's, or a nested object's.
 *
 * One function at every level, which is what makes a nested list state its own
 * item properties instead of stopping at a name.
 * @param schema - the declared properties.
 * @param rules - the component's tightened readings, matched by property name at every level.
 * @returns the summary, one property after another in declaration order.
 */
function describeProps(schema: PropsSchema, rules: SanitizeRules | undefined): string {
  return Object.entries(schema)
    .map(([name, field]) => `${name}${field.required ? '' : '?'}${describeField(field.schema, rules, rules?.[name])}`)
    .join(', ')
}

/**
 * Render one value's declared shape on a line that names no property: an
 * output, and either side of a refused binding.
 *
 * The item notation rather than the property one, because there is no property
 * name for a suffix to hang off. A list also states its bounds, which is what
 * makes two lists of the same items readable as different offers where one is
 * refused for carrying more than the other accepts.
 * @param schema - the declared value.
 * @returns the rendering.
 */
export function describeSchema(schema: PropsFieldSchema): string {
  const shape = describeItem(schema, undefined)
  return schema.kind === 'array' ? `${shape} (${schema.minItems}–${schema.maxItems})` : shape
}

/**
 * Render one component's outputs, as the line under its properties.
 * @param outputs - the values another block may read from it.
 * @returns the line's contents, one output after another in declaration order.
 */
function describeOutputs(outputs: readonly ComponentOutput[]): string {
  return outputs.map(output => `${output.id} ${describeSchema(output.shape)}`).join(', ')
}

/**
 * Render a catalog as model-facing lines.
 *
 * Shared by the tool description and by the refusal an unknown component id
 * gets, so a model that guessed wrong is told the same list it was offered.
 * A component declaring no action says so on its own line rather than in the
 * paragraph below the list: what comes back is a fact about one component, and a
 * model reading the list one line at a time is the reader the line is for.
 *
 * Each component's properties are derived from its own `propsSchema` rather
 * than written beside it, so a component whose schema grows a property offers
 * it in the same edit. Without them the description would be the only place a
 * model could learn a component exists and the last place it could learn what
 * to send it — one refused call per component, every session.
 *
 * A component another block can read from carries a third line naming what it
 * reports and in what form, for the same reason: a binding is refused unless
 * the output exists and the property accepts its form, and both of those are
 * facts of this table.
 * @param catalog - the components a call may place.
 * @returns two lines per component — `- id — label — purpose`, then its properties — and a third for its outputs.
 */
export function describeCatalog(catalog: readonly ComponentCatalogEntry[]): string {
  return catalog
    .map(entry => `- ${entry.id} — ${entry.label} — ${entry.purpose}${entry.actions.length === 0 ? ' Nothing comes back from it.' : ''}`
      + `\n  props: ${describeProps(entry.propsSchema, entry.sanitize)}`
      + (entry.outputs.length === 0 ? '' : `\n  outputs: ${describeOutputs(entry.outputs)}`))
    .join('\n')
}

/**
 * Name the components one validated spec places, in the wording the end user
 * sees on screen.
 * @param nodes - the spec's nodes, in order.
 * @returns the labels joined for a result line; a node naming no catalog entry contributes its raw id.
 */
export function catalogLabels(nodes: readonly ComponentNode[]): string {
  return nodes.map(node => catalogEntry(node.component)?.label ?? node.component).join('、')
}

/** One block a call places: which component, and the properties it is given. */
export interface ComponentNode {
  /** Identity within one spec; unique, and stable across the calls that replace one another. */
  readonly id: string
  /** Catalog id of the component to draw. */
  readonly component: string
  /**
   * The component's declared properties, as validation accepted them.
   *
   * A property bound to another block's output carries the binding itself —
   * `{"$from": "node:<id>.<output>"}` — rather than a value: what it stands for
   * is decided in the seat, where the user's own work is, and never here.
   */
  readonly props: Readonly<Record<string, unknown>>
}

/** How one stack lays its children out. */
export type LayoutDirection = 'row' | 'col'

/** The accepted {@link LayoutDirection} values, in the order a refusal lists them. */
export const LAYOUT_DIRECTIONS: readonly LayoutDirection[] = ['row', 'col']

/** The space one stack leaves between its children. */
export type LayoutGap = 'sm' | 'md' | 'lg'

/** The accepted {@link LayoutGap} values, in the order a refusal lists them. */
export const LAYOUT_GAPS: readonly LayoutGap[] = ['sm', 'md', 'lg']

/**
 * One row or column of the layout tree.
 *
 * The only layout primitive there is. Nesting stacks expresses every
 * arrangement of rectangles a panel of blocks needs, and anything a second
 * primitive would add — a grid, a tab strip — is either that same nesting or a
 * thing the content column already does with entries of its own.
 */
export interface LayoutStack {
  /** Discriminant. */
  readonly node: 'stack'
  /** Whether the children sit beside one another or above one another. */
  readonly dir: LayoutDirection
  /** The space between them; the seat's own default where a call names none. */
  readonly gap?: LayoutGap
  /** Whether children that do not fit move to a further line; off where a call names none. */
  readonly wrap?: boolean
  /**
   * The share of the stack above it this one takes, read exactly as
   * {@link LayoutBlock.flex}; absent for a stack that takes none, and refused
   * on the outermost stack, which sits in no other and so has nothing to take a
   * share of.
   */
  readonly flex?: number
  /** What the stack lays out, in order. */
  readonly children: readonly LayoutChild[]
}

/**
 * The property names one {@link LayoutStack} may carry.
 *
 * Both readings of a layout tree use this list — the host's judgement, which
 * names the key it refused, and the seat's own reading at the wire edge, which
 * answers a stack carrying anything else with the plain column — so a key added
 * to a stack is a key both of them know about.
 */
export const STACK_KEYS: readonly string[] = ['node', 'dir', 'gap', 'wrap', 'flex', 'children']

/** One block placed in the layout, naming a node of the same spec. */
export interface LayoutBlock {
  /** Discriminant. */
  readonly node: 'component'
  /** The `spec.nodes` id this position draws. */
  readonly id: string
  /**
   * The share of its stack's free space this block takes against its siblings,
   * on top of its own size, which is what its basis stays. A block naming none
   * takes none of that space and is drawn at its own size, and a stack with no
   * free space to divide — a column the content panel scrolls — shows no
   * difference between the two.
   *
   * A nested stack asks for its share the same way, under the same name: what
   * divides a row is its children, and a child is either kind.
   */
  readonly flex?: number
}

/** The property names one {@link LayoutBlock} may carry, shared by both readings the way {@link STACK_KEYS} is. */
export const BLOCK_KEYS: readonly string[] = ['node', 'id', 'flex']

/** What one stack may hold: a block, or a further stack. */
export type LayoutChild = LayoutBlock | LayoutStack

/** The root of a layout tree, which is always a stack. */
export type LayoutNode = LayoutStack

/** The one property a bound value carries. */
export const BINDING_KEY = '$from'

/**
 * What one bound property reads.
 *
 * A reference and nothing else: one source block, one of its declared outputs,
 * and optionally one item of it. There is no expression, no condition and no
 * loop, because the value is resolved in the seat over whatever the user has
 * done so far and a layout language evaluated there is a template engine inside
 * the shell's own origin.
 */
export interface ComponentBinding {
  /** Node id of the block the value is read from. */
  readonly sourceId: string
  /** Which of that block's outputs is read. */
  readonly outputId: string
  /** Which item of a list output is taken; absent when the whole value is read. */
  readonly index?: number
}

/** How a bound property's value names what it reads. */
const BINDING_REFERENCE = new RegExp(
  `^node:[\\w-]{1,${MAX_NODE_ID_LENGTH}}\\.[\\w-]{1,${MAX_OUTPUT_ID_LENGTH}}(?:\\[\\d{1,3}\\])?$`,
)

/**
 * Model-facing wording of {@link BINDING_REFERENCE}, spliced into every refusal
 * and description that states it.
 */
export const BINDING_HINT = 'node:<node id>.<output name>, optionally with [index]'

/**
 * Whether one property value is written as a binding at all.
 *
 * Lenient on purpose, and the counterpart of {@link readBinding}: what it
 * decides is what the caller *meant*, so a malformed binding is refused as one
 * rather than as a property of the wrong type, and a value carrying `$from`
 * where a binding is not accepted is refused for being there.
 * @param value - the property value, however malformed.
 * @returns true when the value is an object carrying `$from`.
 */
export function isBindingValue(value: unknown): value is Readonly<Record<string, unknown>> {
  return value !== null && typeof value === 'object' && !Array.isArray(value) && BINDING_KEY in value
}

/**
 * Read the reference one accepted binding carries.
 * @param reference - the `$from` value.
 * @returns what it reads, or `undefined` when it is not a reference at all.
 */
export function parseBindingReference(reference: string): ComponentBinding | undefined {
  if (!BINDING_REFERENCE.test(reference)) return undefined
  const body = reference.slice('node:'.length)
  const dot = body.indexOf('.')
  const sourceId = body.slice(0, dot)
  const rest = body.slice(dot + 1)
  const bracket = rest.indexOf('[')
  if (bracket < 0) return { sourceId, outputId: rest }
  return { sourceId, outputId: rest.slice(0, bracket), index: Number(rest.slice(bracket + 1, -1)) }
}

/**
 * Read one property value as a binding.
 *
 * Strict, because this is the reading the seat resolves and the tightening pass
 * keeps: a binding is one property named `$from` carrying one reference, and
 * anything else is not a binding whatever it was meant to be. The refusals a
 * model reads are `validate.ts`'s, which takes the two readings apart.
 * @param value - the property value, however malformed.
 * @returns what the property reads, or `undefined` when the value is not an accepted binding.
 */
export function readBinding(value: unknown): ComponentBinding | undefined {
  if (!isBindingValue(value)) return undefined
  if (Object.keys(value).length !== 1) return undefined
  const reference = value[BINDING_KEY]
  return typeof reference === 'string' ? parseBindingReference(reference) : undefined
}

/**
 * What one call puts in the column.
 *
 * The nodes are the blocks; the layout, where a call writes one, says how they
 * sit beside one another. A call with no layout is the flat reading it always
 * had — the blocks stacked top to bottom in the order they were written — which
 * is what keeps a spec written before layouts existed drawable.
 */
export interface ComponentSpec {
  /** The blocks to draw, in the order the seat stacks them where no layout says otherwise. */
  readonly nodes: readonly ComponentNode[]
  /** How the blocks are arranged; absent for the flat stack. */
  readonly layout?: LayoutNode
}

/** What the browser seat receives as one `component` entry's payload. */
export interface ComponentSurfacePayload {
  /** The blocks to draw, in order, exactly as validation accepted them. */
  readonly spec: ComponentSpec
}

/** One accepted call: the entry it owns, the line the user reads, and what to draw. */
export interface ComponentCall {
  /** The entry id; a later call naming it replaces this one where the user is looking. */
  readonly id: string
  /** The user-facing line naming the entry in the switcher strip. */
  readonly title: string
  /** The validated spec. */
  readonly spec: ComponentSpec
}

/** One call's arguments as a log carries them, before anything has judged them. */
export interface ComponentCallArguments {
  /** The `id` argument, however malformed. */
  readonly id?: unknown
  /** The `title` argument, however malformed. */
  readonly title?: unknown
  /** The `spec` argument, however malformed. */
  readonly spec?: unknown
}

/**
 * Read one call's arguments from the decoded argument value — the form
 * `tool/code-dispatch-start` records.
 * @param value - the decoded arguments, however malformed.
 * @returns the arguments, or `undefined` when the value is not an argument record at all.
 */
export function readComponentCall(value: unknown): ComponentCallArguments | undefined {
  if (value === null || typeof value !== 'object' || Array.isArray(value)) return undefined
  return value
}

/**
 * Read one call's arguments from the raw argument JSON — the form `tool/call`
 * records.
 * @param argsRaw - the raw argument JSON, however malformed.
 * @returns the arguments, or `undefined` when the JSON is unreadable or is not an argument record.
 */
export function parseComponentCall(argsRaw: string): ComponentCallArguments | undefined {
  let parsed: unknown
  try {
    parsed = JSON.parse(argsRaw)
  } catch (_argumentsAreNotJson) {
    // A log no reader can decode is the only thing this tells us, and the entry
    // it would have produced is the entry the tool already refused.
    return undefined
  }
  return readComponentCall(parsed)
}

/**
 * One action reported back out of a drawn block, as the command line carries it.
 *
 * Every field but `payload` is an identifier the host resolves against the log:
 * the entry, the node inside it, the component that node names, and the action
 * that component declares. Nothing here is displayed as written — see
 * {@link ComponentActionNotice}.
 */
export interface ComponentAction {
  /** The content entry the block belongs to. */
  readonly entryId: string
  /** Catalog id of the component that reported it; must be the one the named node draws. */
  readonly componentId: string
  /** Which of that component's actions occurred. */
  readonly actionId: string
  /** Which node of the entry's spec reported it, so two blocks of one component stay distinguishable. */
  readonly nodeId: string
  /** The action's declared properties, and only those; the seat trims everything else before reporting. */
  readonly payload: Readonly<Record<string, unknown>>
}

/** The action-document properties that must each be a string. */
const ACTION_ID_FIELDS = ['entryId', 'componentId', 'actionId', 'nodeId'] as const

/** Every property an action document may carry, and the only ones read. */
const ACTION_FIELDS: readonly string[] = [...ACTION_ID_FIELDS, 'payload']

/**
 * Read one action document off a decoded value.
 *
 * A document carrying a property this reader does not know is refused whole,
 * the same way {@link ComponentAction.payload} is judged against the action's
 * own declared properties: one rule for both levels of the document, so a seat
 * sending a field nobody reads learns that it did instead of having it
 * silently dropped.
 * @param value - the decoded document, however malformed.
 * @returns the action, or `undefined` when the value is not an action document at all.
 */
export function readComponentAction(value: unknown): ComponentAction | undefined {
  if (value === null || typeof value !== 'object' || Array.isArray(value)) return undefined
  const record = value as Record<string, unknown>
  for (const key of Object.keys(record)) {
    if (!ACTION_FIELDS.includes(key)) return undefined
  }
  for (const field of ACTION_ID_FIELDS) {
    if (typeof record[field] !== 'string') return undefined
  }
  const payload = record['payload']
  if (payload === null || typeof payload !== 'object' || Array.isArray(payload)) return undefined
  return {
    entryId: record['entryId'] as string,
    componentId: record['componentId'] as string,
    actionId: record['actionId'] as string,
    nodeId: record['nodeId'] as string,
    payload: payload as Record<string, unknown>,
  }
}

/**
 * Read one action document off the command's raw input.
 * @param rawInput - everything after the command name, as the invocation carries it.
 * @returns the action, or `undefined` when the input is unreadable or is not an action document.
 */
export function parseComponentActionLine(rawInput: string): ComponentAction | undefined {
  let parsed: unknown
  try {
    parsed = JSON.parse(rawInput)
  } catch (_actionIsNotJson) {
    // Nothing else can reach the reason: the input is one JSON document by
    // construction on the seat, and a line that is not one names no action.
    return undefined
  }
  return readComponentAction(parsed)
}

/**
 * Write the command line that reports one action.
 *
 * The seat's half of the wire contract: both halves ship in this package, so
 * the line is written and read through one pair of functions rather than
 * assembled by hand on either side.
 * @param action - the action to report.
 * @returns the complete command line, leading slash included.
 */
export function formatComponentActionLine(action: ComponentAction): string {
  return `/${COMPONENT_ACTION_COMMAND} ${JSON.stringify(action)}`
}
