/**
 * What one `show_component` call is from outside the tool body, and what one
 * action reported back out of a drawn block is: the wire tool name, the command
 * name the seat reports through, the content kind the call claims, the catalog
 * of components a call may place with the actions each of them reports, and the
 * protocol ceilings both directions are measured against.
 *
 * One home, because three readers must agree on the same rules. The tool
 * refuses a call the seat could not draw; the content-surface extractor decides
 * which logged calls became entries; and the browser seat re-reads the same
 * document at the wire edge, where a value's type is a claim rather than a
 * guarantee. A component the host accepts and the seat refuses is a blank
 * column with nothing said about it, and a ceiling the two halves disagree on
 * is that same failure with an extra round trip in front of it.
 *
 * The module imports nothing, so the node half, the browser bundle, and the
 * session fold all read one copy of the rules.
 * @module @deepseek-ai/dsh-experimental-component-surface/src/component-call
 */

/** The wire tool name this package offers the model. */
export const SHOW_COMPONENT_TOOL_NAME = 'show_component'

/**
 * Command name the browser seat reports one action through. Both halves of the
 * seam live in this package, so both read this constant rather than keeping
 * their own literal copies.
 */
export const COMPONENT_ACTION_COMMAND = 'component-action'

/**
 * `source.plugin` of every notice an action produces.
 *
 * Names the seam the user is looking at — a component in the content column —
 * rather than this package's Cordis plugin name, because it is the id the chat
 * transcript prints beside the collapsed row.
 */
export const COMPONENT_ACTION_PLUGIN = 'content-component'

/**
 * Largest action document, in UTF-8 bytes, that is carried to the model.
 *
 * The command's own record is written verbatim before any handler runs, so this
 * is not a ceiling on what reaches the log — it is the point past which the
 * action is not delivered to the agent at all (see the README's Known
 * Limitations).
 */
export const MAX_ACTION_PAYLOAD_BYTES = 2048

/**
 * Turns actions may open on one agent before a human message refills the
 * budget.
 *
 * A budget rather than a rate: a block whose every press wakes the agent turns
 * a user drumming on a button into an unbounded chain of turns, and the refill
 * is the human's next message, which is the only evidence the chain is still
 * wanted.
 */
export const WAKE_BUDGET = 3

/**
 * Kind key this package owns in the content column, and the `content.surface.kind`
 * slot key its browser seat claims. Written as a literal on both sides: the
 * client slot catalog is generated by scanning for literal keys.
 */
export const COMPONENT_KIND = 'component'

/** Largest accepted entry `id`, in characters. */
export const MAX_ENTRY_ID_LENGTH = 64

/** Largest accepted `title`, in characters. */
export const MAX_TITLE_LENGTH = 24

/** Largest accepted `JSON.stringify(spec)`, in UTF-8 bytes. */
export const MAX_SPEC_BYTES = 65536

/** Largest accepted `spec.nodes` length. */
export const MAX_NODES = 8

/** Largest accepted node `id`, in characters. */
export const MAX_NODE_ID_LENGTH = 32

/** Largest accepted button `id` inside a confirmation bar, in characters. */
export const MAX_BUTTON_ID_LENGTH = 32

/** Characters an entry id, a node id, and a catalog-declared token property may use. */
export const TOKEN_CHARSET = /^[\w-]+$/

/** Model-facing wording of {@link TOKEN_CHARSET}, spliced into every refusal and description that states it. */
export const TOKEN_HINT = 'letters, digits, underscores and hyphens'

/** One restricted string property: bounded length, optionally a restricted alphabet. */
export interface StringFieldSchema {
  /** Discriminant. */
  readonly kind: 'string'
  /** Largest accepted value, in characters. */
  readonly maxLength: number
  /** Alphabet the value is restricted to; absent when any character is accepted. */
  readonly charset?: StringCharset
}

/** An alphabet restriction, together with the wording a refusal states it in. */
export interface StringCharset {
  /** Characters the whole value must match. */
  readonly allowed: RegExp
  /** Model-facing description of {@link allowed}, spliced into the refusal. */
  readonly hint: string
}

/** One property whose value must be one of a fixed set of strings. */
export interface EnumFieldSchema {
  /** Discriminant. */
  readonly kind: 'enum'
  /** The accepted values, in the order a refusal lists them. */
  readonly values: readonly string[]
}

/** One property whose value is a record of further declared properties. */
export interface ObjectFieldSchema {
  /** Discriminant. */
  readonly kind: 'object'
  /** The declared properties; anything else is refused. */
  readonly fields: PropsSchema
}

/**
 * One property whose value is a bounded list of identified records.
 *
 * Items are records rather than scalars, and one of their properties always
 * identifies the item, because that is what every list a component draws is:
 * rows the user can point at. Widen it when a component needs a list of bare
 * values.
 */
export interface ArrayFieldSchema {
  /** Discriminant. */
  readonly kind: 'array'
  /** Schema every item is measured against. */
  readonly item: ObjectFieldSchema
  /** Fewest accepted items. */
  readonly minItems: number
  /** Most accepted items. */
  readonly maxItems: number
  /** Item property that must be unique across the list. */
  readonly uniqueBy: string
}

/**
 * What a declared property may be.
 *
 * The union is the security boundary rather than a convenience: there is no
 * member that can express rich text, a function body, or a URL, so a model
 * cannot write one into a component's props and no sanitizer downstream has to
 * recognize one. Every string reaches the seat as a text value.
 */
export type PropsFieldSchema =
  | StringFieldSchema
  | EnumFieldSchema
  | ObjectFieldSchema
  | ArrayFieldSchema

/** One declared property of a component. */
export interface PropsField {
  /** Whether a call must carry the property. */
  readonly required: boolean
  /** What the value must be. */
  readonly schema: PropsFieldSchema
}

/** A component's declared properties, keyed by property name. */
export type PropsSchema = Readonly<Record<string, PropsField>>

/**
 * What the host does with one reported action.
 *
 * Three grades and no fourth. `silent` is swallowed where it happens; `context`
 * waits in the agent's inbox and is read at its next step; `wake` opens a turn
 * of its own. The grade belongs to the action rather than to a deployment,
 * because it follows from what the gesture means — a sort order is not news, a
 * pressed confirmation is the answer the agent was waiting for — and a
 * deployment that moved it would be changing what the agent is told happened.
 */
export type ActionReport = 'silent' | 'context' | 'wake'

/**
 * Everything one action's account is built from, all of it host-side: the entry
 * as the log recorded it, the node the block was drawn from, and the payload
 * after it passed the action's declared properties.
 *
 * The seat's own text is deliberately absent. What the user pressed is named
 * from the catalog and from the spec the model itself wrote, so a page that
 * lies about its labels cannot put words in the user's mouth.
 */
export interface ComponentActionContext {
  /** The content entry the block belongs to; also what the model reuses to replace it. */
  readonly entryId: string
  /** The entry's user-facing title, as the accepted call wrote it. */
  readonly entryTitle: string
  /** The node the block was drawn from, as validation accepted it. */
  readonly node: ComponentNode
  /** The catalog entry the node names. */
  readonly component: ComponentCatalogEntry
  /** The action's payload, after it passed {@link ComponentActionDefinition.payloadSchema}. */
  readonly payload: Readonly<Record<string, unknown>>
}

/** The two accounts one reported action produces. */
export interface ComponentActionNotice {
  /**
   * What the agent is told, from the agent's own vantage: what the user did,
   * and the entry and node ids to name it by. English, like every other
   * model-facing string in this package; the labels quoted inside it are the
   * end user's own wording.
   */
  readonly text: string
  /** The one line the user reads on the collapsed transcript row. Chinese, like every other user-facing string here. */
  readonly summary: string
}

/** One action a component reports back out of a drawn block. */
export interface ComponentActionDefinition {
  /** Stable id the seat writes in the action document's `actionId`. */
  readonly id: string
  /** What the host does with it. */
  readonly report: ActionReport
  /** The only payload properties this action accepts; anything else is refused, exactly as for a component's props. */
  readonly payloadSchema: PropsSchema
  /**
   * Build the two accounts of one occurrence.
   * @param context - the entry, the node, the catalog entry, and the accepted payload.
   * @returns the accounts, or `undefined` when the payload names nothing the
   *   drawn block actually carries — a press of a button that is not on screen
   *   is reported to nobody.
   */
  readonly describe: (context: ComponentActionContext) => ComponentActionNotice | undefined
}

/** One component a call may place. */
export interface ComponentCatalogEntry {
  /** Stable id the model writes in `spec.nodes[i].component`. */
  readonly id: string
  /** The name the end user reads. Chinese, because it is user-facing copy rather than model-facing text. */
  readonly label: string
  /** One model-facing sentence saying when the component is worth using; spliced into the tool description. */
  readonly purpose: string
  /** The only properties this component accepts. */
  readonly propsSchema: PropsSchema
  /** The only actions this component reports back; empty for a component nothing comes back from. */
  readonly actions: readonly ComponentActionDefinition[]
}

/** Catalog id of the confirmation bar. */
export const CONFIRM_BAR_ID = 'el.confirm-bar'

/** The confirmation bar's declared properties. */
const CONFIRM_BAR_PROPS: PropsSchema = {
  title: { required: false, schema: { kind: 'string', maxLength: 80 } },
  message: { required: false, schema: { kind: 'string', maxLength: 400 } },
  buttons: {
    required: true,
    schema: {
      kind: 'array',
      minItems: 1,
      maxItems: 5,
      uniqueBy: 'id',
      item: {
        kind: 'object',
        fields: {
          id: {
            required: true,
            schema: {
              kind: 'string',
              maxLength: MAX_BUTTON_ID_LENGTH,
              charset: { allowed: TOKEN_CHARSET, hint: TOKEN_HINT },
            },
          },
          label: { required: true, schema: { kind: 'string', maxLength: 16 } },
          tone: { required: false, schema: { kind: 'enum', values: ['primary', 'default', 'danger'] } },
        },
      },
    },
  },
}

/** Action id the confirmation bar reports a button press under. */
export const CONFIRM_BAR_PRESS_ID = 'press'

/**
 * Read one button's user-facing label out of the spec the panel is drawing.
 *
 * The cast is what validation already proved: the node reached here only
 * through the confirmation bar's own `propsSchema`, where `buttons` is a
 * required list whose every item carries a required string `id` and a required
 * string `label`.
 * @param node - the drawn node, as validation accepted it.
 * @param buttonId - the pressed button's id, as the action's payload carried it.
 * @returns the label, or `undefined` when the drawn bar carries no such button.
 */
function buttonLabel(node: ComponentNode, buttonId: unknown): string | undefined {
  const buttons = node.props['buttons'] as readonly { readonly id: string; readonly label: string }[]
  return buttons.find(button => button.id === buttonId)?.label
}

/**
 * The confirmation bar's one action.
 *
 * `wake` because a press is the whole reason the bar was placed: the agent put
 * a decision in front of the user and stopped, and the answer arriving as
 * quiet context would leave it sitting there. The payload carries the button's
 * id and nothing else — the label the notice quotes is read back out of the
 * spec, so the seat cannot report a press of "Cancel" as a press of "Delete".
 */
const CONFIRM_BAR_ACTIONS: readonly ComponentActionDefinition[] = [{
  id: CONFIRM_BAR_PRESS_ID,
  report: 'wake',
  payloadSchema: {
    buttonId: {
      required: true,
      schema: {
        kind: 'string',
        maxLength: MAX_BUTTON_ID_LENGTH,
        charset: { allowed: TOKEN_CHARSET, hint: TOKEN_HINT },
      },
    },
  },
  describe: ({ entryId, entryTitle, node, component, payload }) => {
    const label = buttonLabel(node, payload['buttonId'])
    if (label === undefined) return undefined
    return {
      text: `The user pressed "${label}" in content panel entry "${entryId}" ("${entryTitle}"), on the ${component.label} block "${node.id}".`,
      summary: `用户在「${entryTitle}」里点了「${label}」`,
    }
  },
}]

/**
 * Every component a call may place.
 *
 * A static table rather than a registry service, because one package owns every
 * entry: the seat that draws a kind and the schema that admits it ship
 * together. `as const` is what keeps the ids literal, so {@link CatalogId} is
 * derived from this table instead of restated beside it, and the seat's
 * `satisfies Record<CatalogId, ComponentRenderer>` turns "a catalog entry with
 * no renderer" into a compile error rather than a blank block at runtime.
 * Replace it with a registered seam when a package this one does not own needs
 * to contribute a component.
 */
export const COMPONENT_CATALOG = [
  {
    id: CONFIRM_BAR_ID,
    label: '确认条',
    purpose: 'A short prompt above a row of buttons, for putting one decision in front of the user.',
    propsSchema: CONFIRM_BAR_PROPS,
    actions: CONFIRM_BAR_ACTIONS,
  },
] as const satisfies readonly ComponentCatalogEntry[]

/**
 * Every id {@link COMPONENT_CATALOG} declares, as a union.
 *
 * Derived from the table rather than written beside it: adding a component
 * widens this union in the same edit, which is what makes the seat's renderer
 * table fail to compile until that component has a renderer.
 */
export type CatalogId = (typeof COMPONENT_CATALOG)[number]['id']

/** Levels a spec spends before a declared property's value: the spec object, `nodes`, one node, and its `props`. */
const SPEC_FRAME_DEPTH = 4

/**
 * Levels of nesting one declared property's value adds under `props`.
 * @param field - the declared property.
 * @returns object levels the deepest legal value of this property occupies.
 */
function fieldDepth(field: PropsFieldSchema): number {
  switch (field.kind) {
    case 'string':
    case 'enum': return 0
    case 'object': return 1 + schemaDepth(field.fields)
    case 'array': return 2 + schemaDepth(field.item.fields)
    /* v8 ignore start -- PropsFieldSchema is closed and every variant returns above. */
    default: {
      // Not `assertNever` from dsh-llm, for the reason validate.ts states at its
      // own exhaustiveness check: this module is loaded by the browser seat.
      const unhandled: never = field
      throw new Error(`component-surface: unhandled props schema ${JSON.stringify(unhandled)}`)
    }
    /* v8 ignore stop */
  }
}

/**
 * Levels of nesting the deepest declared property of one schema adds under `props`.
 * @param schema - the declared properties.
 * @returns object levels the deepest legal record of this schema occupies below its own level.
 */
function schemaDepth(schema: PropsSchema): number {
  return Object.values(schema).reduce((deepest, field) => Math.max(deepest, fieldDepth(field.schema)), 0)
}

/**
 * Deepest spec nesting one catalog declares as legal, counting the spec object
 * itself as level one.
 *
 * The ceiling is measured off the catalog rather than written down, so the
 * documents a component declares as legal and the depth a spec is refused at
 * cannot drift apart: a component declaring a nested property widens the
 * ceiling by exactly what that property needs.
 * @param catalog - the components a call may place.
 * @returns levels the deepest legal spec over that catalog occupies.
 */
export function maxSpecDepthOf(catalog: readonly ComponentCatalogEntry[]): number {
  return SPEC_FRAME_DEPTH + catalog.reduce((deepest, entry) => Math.max(deepest, schemaDepth(entry.propsSchema)), 0)
}

/**
 * Deepest accepted nesting inside `spec` for this deployment's catalog.
 *
 * Anything past it is malformed regardless of which component it names, and
 * refusing it bounds the work every later check does.
 */
export const MAX_SPEC_DEPTH = maxSpecDepthOf(COMPONENT_CATALOG)

/**
 * Look one action up on the component that declares it.
 * @param component - the catalog entry the drawn node names.
 * @param actionId - the `actionId` an action document carried, however malformed.
 * @returns the action, or `undefined` when that component reports no such action.
 */
export function catalogAction(component: ComponentCatalogEntry, actionId: unknown): ComponentActionDefinition | undefined {
  return component.actions.find(action => action.id === actionId)
}

/**
 * Look one component up by the id a call named.
 * @param id - the `component` value, however malformed.
 * @returns the catalog entry, or `undefined` when the deployment has no such component.
 */
export function catalogEntry(id: unknown): ComponentCatalogEntry | undefined {
  return COMPONENT_CATALOG.find(entry => entry.id === id)
}

/**
 * Render the whole catalog as model-facing lines.
 *
 * Shared by the tool description and by the refusal an unknown component id
 * gets, so a model that guessed wrong is told the same list it was offered.
 * @returns one `- id — label — purpose` line per component.
 */
export function describeCatalog(): string {
  return COMPONENT_CATALOG.map(entry => `- ${entry.id} — ${entry.label} — ${entry.purpose}`).join('\n')
}

/**
 * Name the components one validated spec places, in the wording the end user
 * sees on screen.
 * @param nodes - the spec's nodes, in order.
 * @returns the labels joined for a result line; a node naming no catalog entry contributes its raw id.
 */
export function catalogLabels(nodes: readonly ComponentNode[]): string {
  return nodes.map(node => catalogEntry(node.component)?.label ?? node.component).join('、')
}

/** One block a call places: which component, and the properties it is given. */
export interface ComponentNode {
  /** Identity within one spec; unique, and stable across the calls that replace one another. */
  readonly id: string
  /** Catalog id of the component to draw. */
  readonly component: string
  /** The component's declared properties, as validation accepted them. */
  readonly props: Readonly<Record<string, unknown>>
}

/**
 * What one call puts in the column.
 *
 * A flat node list: there is no layout tree and no cross-node binding, so a
 * spec says which blocks appear and in what order and nothing else.
 */
export interface ComponentSpec {
  /** The blocks to draw, in the order the seat stacks them. */
  readonly nodes: readonly ComponentNode[]
}

/** What the browser seat receives as one `component` entry's payload. */
export interface ComponentSurfacePayload {
  /** The blocks to draw, in order, exactly as validation accepted them. */
  readonly spec: ComponentSpec
}

/** One accepted call: the entry it owns, the line the user reads, and what to draw. */
export interface ComponentCall {
  /** The entry id; a later call naming it replaces this one where the user is looking. */
  readonly id: string
  /** The user-facing line naming the entry in the switcher strip. */
  readonly title: string
  /** The validated spec. */
  readonly spec: ComponentSpec
}

/** One call's arguments as a log carries them, before anything has judged them. */
export interface ComponentCallArguments {
  /** The `id` argument, however malformed. */
  readonly id?: unknown
  /** The `title` argument, however malformed. */
  readonly title?: unknown
  /** The `spec` argument, however malformed. */
  readonly spec?: unknown
}

/**
 * Read one call's arguments from the decoded argument value — the form
 * `tool/code-dispatch-start` records.
 * @param value - the decoded arguments, however malformed.
 * @returns the arguments, or `undefined` when the value is not an argument record at all.
 */
export function readComponentCall(value: unknown): ComponentCallArguments | undefined {
  if (value === null || typeof value !== 'object' || Array.isArray(value)) return undefined
  return value
}

/**
 * Read one call's arguments from the raw argument JSON — the form `tool/call`
 * records.
 * @param argsRaw - the raw argument JSON, however malformed.
 * @returns the arguments, or `undefined` when the JSON is unreadable or is not an argument record.
 */
export function parseComponentCall(argsRaw: string): ComponentCallArguments | undefined {
  let parsed: unknown
  try {
    parsed = JSON.parse(argsRaw)
  } catch (_argumentsAreNotJson) {
    // A log no reader can decode is the only thing this tells us, and the entry
    // it would have produced is the entry the tool already refused.
    return undefined
  }
  return readComponentCall(parsed)
}

/**
 * One action reported back out of a drawn block, as the command line carries it.
 *
 * Every field but `payload` is an identifier the host resolves against the log:
 * the entry, the node inside it, the component that node names, and the action
 * that component declares. Nothing here is displayed as written — see
 * {@link ComponentActionNotice}.
 */
export interface ComponentAction {
  /** The content entry the block belongs to. */
  readonly entryId: string
  /** Catalog id of the component that reported it; must be the one the named node draws. */
  readonly componentId: string
  /** Which of that component's actions occurred. */
  readonly actionId: string
  /** Which node of the entry's spec reported it, so two blocks of one component stay distinguishable. */
  readonly nodeId: string
  /** The action's declared properties, and only those; the seat trims everything else before reporting. */
  readonly payload: Readonly<Record<string, unknown>>
}

/** The action-document properties that must each be a string. */
const ACTION_ID_FIELDS = ['entryId', 'componentId', 'actionId', 'nodeId'] as const

/** Every property an action document may carry, and the only ones read. */
const ACTION_FIELDS: readonly string[] = [...ACTION_ID_FIELDS, 'payload']

/**
 * Read one action document off a decoded value.
 *
 * A document carrying a property this reader does not know is refused whole,
 * the same way {@link ComponentAction.payload} is judged against the action's
 * own declared properties: one rule for both levels of the document, so a seat
 * sending a field nobody reads learns that it did instead of having it
 * silently dropped.
 * @param value - the decoded document, however malformed.
 * @returns the action, or `undefined` when the value is not an action document at all.
 */
export function readComponentAction(value: unknown): ComponentAction | undefined {
  if (value === null || typeof value !== 'object' || Array.isArray(value)) return undefined
  const record = value as Record<string, unknown>
  for (const key of Object.keys(record)) {
    if (!ACTION_FIELDS.includes(key)) return undefined
  }
  for (const field of ACTION_ID_FIELDS) {
    if (typeof record[field] !== 'string') return undefined
  }
  const payload = record['payload']
  if (payload === null || typeof payload !== 'object' || Array.isArray(payload)) return undefined
  return {
    entryId: record['entryId'] as string,
    componentId: record['componentId'] as string,
    actionId: record['actionId'] as string,
    nodeId: record['nodeId'] as string,
    payload: payload as Record<string, unknown>,
  }
}

/**
 * Read one action document off the command's raw input.
 * @param rawInput - everything after the command name, as the invocation carries it.
 * @returns the action, or `undefined` when the input is unreadable or is not an action document.
 */
export function parseComponentActionLine(rawInput: string): ComponentAction | undefined {
  let parsed: unknown
  try {
    parsed = JSON.parse(rawInput)
  } catch (_actionIsNotJson) {
    // Nothing else can reach the reason: the input is one JSON document by
    // construction on the seat, and a line that is not one names no action.
    return undefined
  }
  return readComponentAction(parsed)
}

/**
 * Write the command line that reports one action.
 *
 * The seat's half of the wire contract: both halves ship in this package, so
 * the line is written and read through one pair of functions rather than
 * assembled by hand on either side.
 * @param action - the action to report.
 * @returns the complete command line, leading slash included.
 */
export function formatComponentActionLine(action: ComponentAction): string {
  return `/${COMPONENT_ACTION_COMMAND} ${JSON.stringify(action)}`
}
