/**
 * What one `show_component` call is from outside the tool body: the wire tool
 * name, the content kind the call claims, the catalog of components a call may
 * place, and the protocol ceilings a spec is measured against.
 *
 * One home, because three readers must agree on the same rules. The tool
 * refuses a call the seat could not draw; the content-surface extractor decides
 * which logged calls became entries; and the browser seat re-reads the same
 * document at the wire edge, where a value's type is a claim rather than a
 * guarantee. A component the host accepts and the seat refuses is a blank
 * column with nothing said about it, and a ceiling the two halves disagree on
 * is that same failure with an extra round trip in front of it.
 *
 * The module imports nothing, so the node half, the browser bundle, and the
 * session fold all read one copy of the rules.
 * @module @deepseek-ai/dsh-experimental-component-surface/src/component-call
 */

/** The wire tool name this package offers the model. */
export const SHOW_COMPONENT_TOOL_NAME = 'show_component'

/**
 * Kind key this package owns in the content column, and the `content.surface.kind`
 * slot key its browser seat claims. Written as a literal on both sides: the
 * client slot catalog is generated by scanning for literal keys.
 */
export const COMPONENT_KIND = 'component'

/** Largest accepted entry `id`, in characters. */
export const MAX_ENTRY_ID_LENGTH = 64

/** Largest accepted `title`, in characters. */
export const MAX_TITLE_LENGTH = 24

/** Largest accepted `JSON.stringify(spec)`, in UTF-8 bytes. */
export const MAX_SPEC_BYTES = 65536

/** Largest accepted `spec.nodes` length. */
export const MAX_NODES = 8

/** Largest accepted node `id`, in characters. */
export const MAX_NODE_ID_LENGTH = 32

/** Largest accepted button `id` inside a confirmation bar, in characters. */
export const MAX_BUTTON_ID_LENGTH = 32

/** Characters an entry id, a node id, and a catalog-declared token property may use. */
export const TOKEN_CHARSET = /^[\w-]+$/

/** Model-facing wording of {@link TOKEN_CHARSET}, spliced into every refusal and description that states it. */
export const TOKEN_HINT = 'letters, digits, underscores and hyphens'

/** One restricted string property: bounded length, optionally a restricted alphabet. */
export interface StringFieldSchema {
  /** Discriminant. */
  readonly kind: 'string'
  /** Largest accepted value, in characters. */
  readonly maxLength: number
  /** Alphabet the value is restricted to; absent when any character is accepted. */
  readonly charset?: StringCharset
}

/** An alphabet restriction, together with the wording a refusal states it in. */
export interface StringCharset {
  /** Characters the whole value must match. */
  readonly allowed: RegExp
  /** Model-facing description of {@link allowed}, spliced into the refusal. */
  readonly hint: string
}

/** One property whose value must be one of a fixed set of strings. */
export interface EnumFieldSchema {
  /** Discriminant. */
  readonly kind: 'enum'
  /** The accepted values, in the order a refusal lists them. */
  readonly values: readonly string[]
}

/** One property whose value is a record of further declared properties. */
export interface ObjectFieldSchema {
  /** Discriminant. */
  readonly kind: 'object'
  /** The declared properties; anything else is refused. */
  readonly fields: PropsSchema
}

/**
 * One property whose value is a bounded list of identified records.
 *
 * Items are records rather than scalars, and one of their properties always
 * identifies the item, because that is what every list a component draws is:
 * rows the user can point at. Widen it when a component needs a list of bare
 * values.
 */
export interface ArrayFieldSchema {
  /** Discriminant. */
  readonly kind: 'array'
  /** Schema every item is measured against. */
  readonly item: ObjectFieldSchema
  /** Fewest accepted items. */
  readonly minItems: number
  /** Most accepted items. */
  readonly maxItems: number
  /** Item property that must be unique across the list. */
  readonly uniqueBy: string
}

/**
 * What a declared property may be.
 *
 * The union is the security boundary rather than a convenience: there is no
 * member that can express rich text, a function body, or a URL, so a model
 * cannot write one into a component's props and no sanitizer downstream has to
 * recognize one. Every string reaches the seat as a text value.
 */
export type PropsFieldSchema =
  | StringFieldSchema
  | EnumFieldSchema
  | ObjectFieldSchema
  | ArrayFieldSchema

/** One declared property of a component. */
export interface PropsField {
  /** Whether a call must carry the property. */
  readonly required: boolean
  /** What the value must be. */
  readonly schema: PropsFieldSchema
}

/** A component's declared properties, keyed by property name. */
export type PropsSchema = Readonly<Record<string, PropsField>>

/** One component a call may place. */
export interface ComponentCatalogEntry {
  /** Stable id the model writes in `spec.nodes[i].component`. */
  readonly id: string
  /** The name the end user reads. Chinese, because it is user-facing copy rather than model-facing text. */
  readonly label: string
  /** One model-facing sentence saying when the component is worth using; spliced into the tool description. */
  readonly purpose: string
  /** The only properties this component accepts. */
  readonly propsSchema: PropsSchema
}

/** Catalog id of the confirmation bar. */
export const CONFIRM_BAR_ID = 'el.confirm-bar'

/** The confirmation bar's declared properties. */
const CONFIRM_BAR_PROPS: PropsSchema = {
  title: { required: false, schema: { kind: 'string', maxLength: 80 } },
  message: { required: false, schema: { kind: 'string', maxLength: 400 } },
  buttons: {
    required: true,
    schema: {
      kind: 'array',
      minItems: 1,
      maxItems: 5,
      uniqueBy: 'id',
      item: {
        kind: 'object',
        fields: {
          id: {
            required: true,
            schema: {
              kind: 'string',
              maxLength: MAX_BUTTON_ID_LENGTH,
              charset: { allowed: TOKEN_CHARSET, hint: TOKEN_HINT },
            },
          },
          label: { required: true, schema: { kind: 'string', maxLength: 16 } },
          tone: { required: false, schema: { kind: 'enum', values: ['primary', 'default', 'danger'] } },
        },
      },
    },
  },
}

/**
 * Every component a call may place.
 *
 * A static table rather than a registry service, because one package owns every
 * entry: the seat that draws a kind and the schema that admits it ship
 * together. `as const` is what keeps the ids literal, so {@link CatalogId} is
 * derived from this table instead of restated beside it, and the seat's
 * `satisfies Record<CatalogId, ComponentRenderer>` turns "a catalog entry with
 * no renderer" into a compile error rather than a blank block at runtime.
 * Replace it with a registered seam when a package this one does not own needs
 * to contribute a component.
 */
export const COMPONENT_CATALOG = [
  {
    id: CONFIRM_BAR_ID,
    label: '确认条',
    purpose: 'A short prompt above a row of buttons, for putting one decision in front of the user.',
    propsSchema: CONFIRM_BAR_PROPS,
  },
] as const satisfies readonly ComponentCatalogEntry[]

/**
 * Every id {@link COMPONENT_CATALOG} declares, as a union.
 *
 * Derived from the table rather than written beside it: adding a component
 * widens this union in the same edit, which is what makes the seat's renderer
 * table fail to compile until that component has a renderer.
 */
export type CatalogId = (typeof COMPONENT_CATALOG)[number]['id']

/** Levels a spec spends before a declared property's value: the spec object, `nodes`, one node, and its `props`. */
const SPEC_FRAME_DEPTH = 4

/**
 * Levels of nesting one declared property's value adds under `props`.
 * @param field - the declared property.
 * @returns object levels the deepest legal value of this property occupies.
 */
function fieldDepth(field: PropsFieldSchema): number {
  switch (field.kind) {
    case 'string':
    case 'enum': return 0
    case 'object': return 1 + schemaDepth(field.fields)
    case 'array': return 2 + schemaDepth(field.item.fields)
    /* v8 ignore start -- PropsFieldSchema is closed and every variant returns above. */
    default: {
      // Not `assertNever` from dsh-llm, for the reason validate.ts states at its
      // own exhaustiveness check: this module is loaded by the browser seat.
      const unhandled: never = field
      throw new Error(`component-surface: unhandled props schema ${JSON.stringify(unhandled)}`)
    }
    /* v8 ignore stop */
  }
}

/**
 * Levels of nesting the deepest declared property of one schema adds under `props`.
 * @param schema - the declared properties.
 * @returns object levels the deepest legal record of this schema occupies below its own level.
 */
function schemaDepth(schema: PropsSchema): number {
  return Object.values(schema).reduce((deepest, field) => Math.max(deepest, fieldDepth(field.schema)), 0)
}

/**
 * Deepest spec nesting one catalog declares as legal, counting the spec object
 * itself as level one.
 *
 * The ceiling is measured off the catalog rather than written down, so the
 * documents a component declares as legal and the depth a spec is refused at
 * cannot drift apart: a component declaring a nested property widens the
 * ceiling by exactly what that property needs.
 * @param catalog - the components a call may place.
 * @returns levels the deepest legal spec over that catalog occupies.
 */
export function maxSpecDepthOf(catalog: readonly ComponentCatalogEntry[]): number {
  return SPEC_FRAME_DEPTH + catalog.reduce((deepest, entry) => Math.max(deepest, schemaDepth(entry.propsSchema)), 0)
}

/**
 * Deepest accepted nesting inside `spec` for this deployment's catalog.
 *
 * Anything past it is malformed regardless of which component it names, and
 * refusing it bounds the work every later check does.
 */
export const MAX_SPEC_DEPTH = maxSpecDepthOf(COMPONENT_CATALOG)

/**
 * Look one component up by the id a call named.
 * @param id - the `component` value, however malformed.
 * @returns the catalog entry, or `undefined` when the deployment has no such component.
 */
export function catalogEntry(id: unknown): ComponentCatalogEntry | undefined {
  return COMPONENT_CATALOG.find(entry => entry.id === id)
}

/**
 * Render the whole catalog as model-facing lines.
 *
 * Shared by the tool description and by the refusal an unknown component id
 * gets, so a model that guessed wrong is told the same list it was offered.
 * @returns one `- id — label — purpose` line per component.
 */
export function describeCatalog(): string {
  return COMPONENT_CATALOG.map(entry => `- ${entry.id} — ${entry.label} — ${entry.purpose}`).join('\n')
}

/**
 * Name the components one validated spec places, in the wording the end user
 * sees on screen.
 * @param nodes - the spec's nodes, in order.
 * @returns the labels joined for a result line; a node naming no catalog entry contributes its raw id.
 */
export function catalogLabels(nodes: readonly ComponentNode[]): string {
  return nodes.map(node => catalogEntry(node.component)?.label ?? node.component).join('、')
}

/** One block a call places: which component, and the properties it is given. */
export interface ComponentNode {
  /** Identity within one spec; unique, and stable across the calls that replace one another. */
  readonly id: string
  /** Catalog id of the component to draw. */
  readonly component: string
  /** The component's declared properties, as validation accepted them. */
  readonly props: Readonly<Record<string, unknown>>
}

/**
 * What one call puts in the column.
 *
 * A flat node list: there is no layout tree and no cross-node binding, so a
 * spec says which blocks appear and in what order and nothing else.
 */
export interface ComponentSpec {
  /** The blocks to draw, in the order the seat stacks them. */
  readonly nodes: readonly ComponentNode[]
}

/** What the browser seat receives as one `component` entry's payload. */
export interface ComponentSurfacePayload {
  /** The blocks to draw, in order, exactly as validation accepted them. */
  readonly spec: ComponentSpec
}

/** One accepted call: the entry it owns, the line the user reads, and what to draw. */
export interface ComponentCall {
  /** The entry id; a later call naming it replaces this one where the user is looking. */
  readonly id: string
  /** The user-facing line naming the entry in the switcher strip. */
  readonly title: string
  /** The validated spec. */
  readonly spec: ComponentSpec
}

/** One call's arguments as a log carries them, before anything has judged them. */
export interface ComponentCallArguments {
  /** The `id` argument, however malformed. */
  readonly id?: unknown
  /** The `title` argument, however malformed. */
  readonly title?: unknown
  /** The `spec` argument, however malformed. */
  readonly spec?: unknown
}

/**
 * Read one call's arguments from the decoded argument value — the form
 * `tool/code-dispatch-start` records.
 * @param value - the decoded arguments, however malformed.
 * @returns the arguments, or `undefined` when the value is not an argument record at all.
 */
export function readComponentCall(value: unknown): ComponentCallArguments | undefined {
  if (value === null || typeof value !== 'object' || Array.isArray(value)) return undefined
  return value
}

/**
 * Read one call's arguments from the raw argument JSON — the form `tool/call`
 * records.
 * @param argsRaw - the raw argument JSON, however malformed.
 * @returns the arguments, or `undefined` when the JSON is unreadable or is not an argument record.
 */
export function parseComponentCall(argsRaw: string): ComponentCallArguments | undefined {
  let parsed: unknown
  try {
    parsed = JSON.parse(argsRaw)
  } catch (_argumentsAreNotJson) {
    // A log no reader can decode is the only thing this tells us, and the entry
    // it would have produced is the entry the tool already refused.
    return undefined
  }
  return readComponentCall(parsed)
}
